### ISSUE TITLE
LibWeb/CSS: `has<T>()` assertion failure in `parse_pseudo_simple_selector`

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#14142]
For example:
```
:lang(\xff()\xf8(mA)){
```
Note that those are hex escapes, they have to be replaced with their corresponding byte.
File: [crash-3a873d379544e1b595b0237dbc4edfd4fe9a5162.txt](https://github.com/SerenityOS/serenity/files/8794425/crash-3a873d379544e1b595b0237dbc4edfd4fe9a5162.txt)
```
FuzzCSSParser: ../../../../AK/Variant.h:381: const T &AK::Variant<Web::CSS::Parser::Token, AK::NonnullRefPtr<Web::CSS::Parser::Function>, AK::NonnullRefPtr<Web::CSS::Parser::Block>>::get() const [Ts = <Web::CSS::Parser::Token, AK::NonnullRefPtr<Web::CSS::Parser::Function>, AK::NonnullRefPtr<Web::CSS::Parser::Block>>, T = Web::CSS::Parser::Token]: Assertion `has<T>()' failed.
==125256== ERROR: libFuzzer: deadly signal
    #0 0x4dc021 in __sanitizer_print_stack_trace (/home/lukew/Desktop/serenity-project/serenity/Meta/Lagom/Build/lagom-fuzzers/Fuzzers/FuzzCSSParser+0x4dc021)
    #1 0x456cf7 in fuzzer::PrintStackTrace() (/home/lukew/Desktop/serenity-project/serenity/Meta/Lagom/Build/lagom-fuzzers/Fuzzers/FuzzCSSParser+0x456cf7)
    #2 0x43acc3 in fuzzer::Fuzzer::CrashCallback() (/home/lukew/Desktop/serenity-project/serenity/Meta/Lagom/Build/lagom-fuzzers/Fuzzers/FuzzCSSParser+0x43acc3)
    #3 0x7fe444f3641f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f)
    #4 0x7fe444d0b00a in __libc_signal_restore_set /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #5 0x7fe444d0b00a in raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #6 0x7fe444cea858 in abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79:7
    #7 0x7fe444cea728 in __assert_fail_base /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:92:3
    #8 0x7fe444cfbfd5 in __assert_fail /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:101:3
    #9 0x7fe44e75f82e in Web::CSS::Parser::Token const& AK::Variant<Web::CSS::Parser::Token, AK::NonnullRefPtr<Web::CSS::Parser::Function>, AK::NonnullRefPtr<Web::CSS::Parser::Block> >::get<Web::CSS::Parser::Token>() const /home/lukew/Desktop/serenity-project/serenity/Meta/Lagom/Build/lagom-fuzzers/../../../../AK/Variant.h:381:9
    #10 0x7fe44ed71fb3 in Web::CSS::Parser::Parser::parse_pseudo_simple_selector(Web::CSS::Parser::TokenStream<Web::CSS::Parser::ComponentValue>&) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:625:63
    #11 0x7fe44ed6ccc1 in Web::CSS::Parser::Parser::parse_simple_selector(Web::CSS::Parser::TokenStream<Web::CSS::Parser::ComponentValue>&) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:716:16
    #12 0x7fe44ed6a25b in Web::CSS::Parser::Parser::parse_compound_selector(Web::CSS::Parser::TokenStream<Web::CSS::Parser::ComponentValue>&) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:277:26
    #13 0x7fe44ed687b7 in Web::CSS::Parser::Parser::parse_complex_selector(Web::CSS::Parser::TokenStream<Web::CSS::Parser::ComponentValue>&, Web::CSS::Parser::Parser::SelectorType) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:242:27
    #14 0x7fe44ed74999 in AK::ErrorOr<AK::NonnullRefPtrVector<Web::CSS::Selector, 0ul>, Web::CSS::Parser::Parser::ParseError> Web::CSS::Parser::Parser::parse_a_selector_list<Web::CSS::Parser::ComponentValue>(Web::CSS::Parser::TokenStream<Web::CSS::Parser::ComponentValue>&, Web::CSS::Parser::Parser::SelectorType, Web::CSS::Parser::Parser::SelectorParsingMode) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:223:25
    #15 0x7fe44ed5fe38 in Web::CSS::Parser::Parser::convert_to_rule(AK::NonnullRefPtr<Web::CSS::Parser::Rule>) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:2442:26
    #16 0x7fe44ed5e2c6 in Web::CSS::Parser::Parser::parse_as_css_stylesheet(AK::Optional<AK::URL>) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:188:21
    #17 0x7fe44ee1132c in Web::parse_css_stylesheet(Web::CSS::Parser::ParsingContext const&, AK::StringView, AK::Optional<AK::URL>) /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp:5905:19
```

**Comment by awesomekling** [comment]
Unable to reproduce.
