### ISSUE TITLE
LibJS: The garbage collector's stack scanning does not work with ASAN

### ISSUE THREAD

**Issue by trflynn89** [SerenityOS/serenity#17163]
If you build Lagom test-js with Clang, enable the sanitizers (`-DENABLE_UNDEFINED_SANITIZER=ON -DDENABLE_ADDRESS_SANITIZER=ON`), and enable the garbage-collect-on-every-allocation flag (`test-js -g`), you will quickly hit a UAF error such as:

```
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:234:49: runtime error: member call on address 0x62d0000195f8 which does not point to an object of type 'JS::Object'
0x62d0000195f8: note: object is of type 'JS::HeapBlock::FreelistEntry'
 00 00 00 00  d0 50 90 f9 f9 7f 00 00  04 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'JS::HeapBlock::FreelistEntry'
    #0 0x7ff9f8aca990 in JS::ECMAScriptFunctionObject::internal_construct(JS::MarkedVector<JS::Value, 32ul>, JS::FunctionObject&) Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:234:49
    #1 0x7ff9f89538bf in JS::construct_impl(JS::VM&, JS::FunctionObject&, AK::Optional<JS::MarkedVector<JS::Value, 32ul>>, JS::FunctionObject*) Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp:86:21
    #2 0x7ff9f858829c in construct Meta/Lagom/../../Userland/Libraries/LibJS/Runtime/AbstractOperations.h:135:12
    #3 0x7ff9f858829c in JS::NewExpression::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:420:20
    #4 0x7ff9f858ec08 in JS::ReturnStatement::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:572:18
    #5 0x7ff9f8581b59 in JS::ScopeNode::evaluate_statements(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:110:27
    #6 0x7ff9f858432a in JS::FunctionBody::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:227:12
    #7 0x7ff9f8ac78c2 in JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:893:46
    #8 0x7ff9f8ac2f7f in JS::ECMAScriptFunctionObject::internal_call(JS::Value, JS::MarkedVector<JS::Value, 32ul>) Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:176:19
    #9 0x7ff9f8952c48 in JS::call_impl(JS::VM&, JS::FunctionObject&, JS::Value, AK::Optional<JS::MarkedVector<JS::Value, 32ul>>) Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp:71:21
    #10 0x7ff9f858befa in call Meta/Lagom/../../Userland/Libraries/LibJS/Runtime/AbstractOperations.h:100:12
    #11 0x7ff9f858befa in JS::CallExpression::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:474:12
    #12 0x7ff9f85a6264 in JS::MemberExpression::to_reference(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:1560:22
    #13 0x7ff9f858b760 in JS::CallExpression::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:451:29
    #14 0x7ff9f8587099 in JS::ExpressionStatement::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:349:26
    #15 0x7ff9f8581b59 in JS::ScopeNode::evaluate_statements(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:110:27
    #16 0x7ff9f858432a in JS::FunctionBody::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:227:12
    #17 0x7ff9f8ac78c2 in JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:893:46
    #18 0x7ff9f8ac2f7f in JS::ECMAScriptFunctionObject::internal_call(JS::Value, JS::MarkedVector<JS::Value, 32ul>) Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:176:19
    #19 0x7ff9f8952c48 in JS::call_impl(JS::VM&, JS::FunctionObject&, JS::Value, AK::Optional<JS::MarkedVector<JS::Value, 32ul>>) Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp:71:21
    #20 0x7ff9f858befa in call Meta/Lagom/../../Userland/Libraries/LibJS/Runtime/AbstractOperations.h:100:12
    #21 0x7ff9f858befa in JS::CallExpression::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:474:12
    #22 0x7ff9f8587099 in JS::ExpressionStatement::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:349:26
    #23 0x7ff9f8581b59 in JS::ScopeNode::evaluate_statements(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:110:27
    #24 0x7ff9f85846b0 in JS::BlockStatement::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:241:16
    #25 0x7ff9f85ef61d in JS::TryStatement::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:4026:34
    #26 0x7ff9f8581b59 in JS::ScopeNode::evaluate_statements(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:110:27
    #27 0x7ff9f858432a in JS::FunctionBody::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:227:12
    #28 0x7ff9f8ac78c2 in JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:893:46
    #29 0x7ff9f8ac2f7f in JS::ECMAScriptFunctionObject::internal_call(JS::Value, JS::MarkedVector<JS::Value, 32ul>) Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp:176:19
    #30 0x7ff9f8952c48 in JS::call_impl(JS::VM&, JS::FunctionObject&, JS::Value, AK::Optional<JS::MarkedVector<JS::Value, 32ul>>) Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp:71:21
    #31 0x7ff9f858befa in call Meta/Lagom/../../Userland/Libraries/LibJS/Runtime/AbstractOperations.h:100:12
    #32 0x7ff9f858befa in JS::CallExpression::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:474:12
    #33 0x7ff9f8587099 in JS::ExpressionStatement::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:349:26
    #34 0x7ff9f8581b59 in JS::ScopeNode::evaluate_statements(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:110:27
    #35 0x7ff9f85850ea in JS::Program::execute(JS::Interpreter&) const Userland/Libraries/LibJS/AST.cpp:263:12
    #36 0x7ff9f87b14de in JS::Interpreter::run(JS::Script&, JS::GCPtr<JS::Environment>) Userland/Libraries/LibJS/Interpreter.cpp:89:25
    #37 0x55e471a07ec8 in Test::JS::TestRunner::run_file_test(AK::DeprecatedString const&) Meta/Lagom/../../Userland/Libraries/LibTest/JavaScriptTestRunner.h:392:41
    #38 0x55e471a0200f in Test::JS::TestRunner::do_run_single_test(AK::DeprecatedString const&, unsigned long, unsigned long) Meta/Lagom/../../Userland/Libraries/LibTest/JavaScriptTestRunner.h:270:24
    #39 0x55e4719fd187 in Test::TestRunner::run(AK::DeprecatedString) Meta/Lagom/../../Userland/Libraries/LibTest/TestRunner.h:102:9
    #40 0x55e4719fbb33 in main Userland/Libraries/LibTest/JavaScriptTestRunnerMain.cpp:191:17
    #41 0x7ff9f6e2350f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #42 0x7ff9f6e235c8 in __libc_start_main csu/../csu/libc-start.c:381:3
    #43 0x55e47191a534 in _start (Build/lagom/test-js+0x52534) (BuildId: a2401d73e0a262fa5eb83f9aac890606af7e2fc5)
```

The stack scanning in Userland/Libraries/LibJS/Heap/Heap.cpp `gather_conservative_roots` does not find objects that were recently allocated. In the above trace, that object is allocated here:
https://github.com/SerenityOS/serenity/blob/541637e15aa395ca571222aa15015533ae8f5f4b/Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp#L211

So when GC runs on the next allocation, `this_argument` is collected because it was not found on the stack.

GCC does not have this issue.

**Comment by awesomekling** [comment]
I suspect this happens because of ASAN fake stacks. If we have pointers to objects in the fake stack, we're not gonna find it by looking only at the regular stack like we do now.

There's an API for getting at the fake stacks: https://github.com/llvm/llvm-project/commit/1ee681305f1ddf2fd82e2ff5acb0d711ba23879b

V8 uses this API, so maybe we could use it too.
