### ISSUE TITLE
XML: exponential recursion

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18044]
When fuzzing `FuzzXML` at 4f496e97, I discovered a potential mishandling of pathological input.

```
<!DOCTYPE x[<!ELEMENT x ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
```

The execution time doubles every time a new `(` is appended to the input buffer. For example, the above 119-byte input takes more than 60 seconds and 2GiB of memory to run.

It seems that the recursive descent parser takes too many time trying the choices. Ideally, a one-pass LR parser could be used.

```
#460 operator() ()
    at /root/build/serenity/Userland/Libraries/LibXML/Parser/Parser.cpp:1285
1285                    if (auto result = parse_choice(); !result.is_error())
(gdb) up
#461 operator() ()
    at /root/build/serenity/Userland/Libraries/LibXML/Parser/Parser.cpp:1300
1300                    auto sub_entry = TRY(parse_cp_init());
(gdb)
#462 0x0000555555680b49 in operator() ()
    at /root/build/serenity/Userland/Libraries/LibXML/Parser/Parser.cpp:1316
1316                    choices.append(TRY(parse_cp()));
(gdb)
#463 call () at /root/build/serenity/Meta/Lagom/../../AK/Function.h:173
173                 return m_callable(forward<In>(in)...);
(gdb)
#464 0x000055555566e537 in operator() ()
    at /root/build/serenity/Meta/Lagom/../../AK/Function.h:111
111             return wrapper->call(forward<In>(in)...);
(gdb)
#465 parse_content_spec ()
    at /root/build/serenity/Userland/Libraries/LibXML/Parser/Parser.cpp:1368
1368                if (auto result = parse_choice(); !result.is_error()) {
```

**Comment by AbdelAzizMohamedMousa** [comment]
Thank you for reporting this potential issue. It seems like the input you provided causes the parser to take an exponentially long time, which could lead to a denial-of-service attack. A possible solution would be to switch to a more efficient parsing algorithm, such as an LR parser. You could also consider adding a timeout mechanism to abort the parsing process if it takes too long.

I would recommend reporting this issue to the maintainers of FuzzXML so that they can investigate and possibly fix the issue. It's also a good practice to provide a smaller input that reproduces the issue, as it can help developers isolate the problem more quickly.
