### ISSUE TITLE
TTF: Assertion failure in OpenType::Head::index_to_loc_format

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18303]
When fuzzing FuzzTTF, we found that the program crashed with SIGABRT:

```
FuzzTTF: /root/build/serenity/Userland/Libraries/LibGfx/Font/OpenType/Font.cpp:108: OpenType::IndexToLocFormat OpenType::Head::index_to_loc_format() const: Assertion `false' failed.
[1]    3717532 IOT instruction  ../../Fuzzers-AFLpp-ASan-UBSan/FuzzTTF ../fuzz-ttf-cmin/abrt.out
```

Here's the stack trace:
```
#5  0x000055555571b473 in OpenType::Head::index_to_loc_format (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan-UBSan/FuzzTTF)
                       100: enum OpenType::Head::index_to_loc_format(this = (const class OpenType::Head *)0x1555535001a0) {
                       |||:
                       106:         return IndexToLocFormat::Offset32;
                       107:     default:
                       108:         VERIFY_NOT_REACHED();
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibGfx/Font/OpenType/Font.cpp:108

#6  0x000055555572338a in OpenType::Font::try_load_from_offset (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan-UBSan/FuzzTTF)
                       384: class OpenType::Font::try_load_from_offset(buffer = (AK::ReadonlyBytes){<AK::Detail::Span<unsigned char cons
t>> = {m_values = <optimized out>, m_size = <optimized out>}, <No data fields>}, offset = (u32)0) {
                       |||:
                       |||: /* Local reference: class AK::Optional<OpenType::Loca> loca = {m_storage = '\000' <repeats 23 times>, m_has_
value = false}; */
                       |||: /* Local reference: class AK::Optional<AK::Span<unsigned char const> > opt_loca_slice = {m_storage = "\000ho
RU\025\000\000\000\000\000\000\000\000\000", m_has_value = true}; */
                       |||: /* Local reference: class OpenType::Maxp maxp = {m_slice = {<AK::Detail::Span<unsigned char const>> = {m_val
ues = 0x1555526f6808 "", m_size = 32}, <No data fields>}}; */
                       |||: /* Local reference: class OpenType::Head head = {m_slice = {<AK::Detail::Span<unsigned char const>> = {m_val
ues = 0x1555526f68ac "", m_size = 54}, <No data fields>}}; */
                       495:     Optional<Loca> loca;
                       496:     if (opt_loca_slice.has_value()) {
                       497:         loca = Loca::from_slice(opt_loca_slice.value(), maxp.num_glyphs(), head.index_to_loc_format());
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibGfx/Font/OpenType/Font.cpp:497

#7  0x0000555555721209 in OpenType::Font::try_load_from_externally_owned_memory (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan-
UBSan/FuzzTTF)
                       360: class OpenType::Font::try_load_from_externally_owned_memory(buffer = (AK::ReadonlyBytes){<AK::Detail::Span<u
nsigned char const>> = {m_values = 0x38b79d <error: Cannot access memory at address 0x38b79d>, m_size = 6}, <No data fields>}, index = (
unsigned int)<optimized out>) {
                       |||:
                       |||: /* Local reference: AK::ReadonlyBytes buffer = {<AK::Detail::Span<unsigned char const>> = {m_values = 0x38b7
9d <error: Cannot access memory at address 0x38b79d>, m_size = 6}, <No data fields>}; */
                       378:         return Error::from_string_literal("Not a valid font");
                       379:
                       380:     return try_load_from_offset(buffer, 0);
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibGfx/Font/OpenType/Font.cpp:380
```

You can reproduce the bug with the following input (base64 encoded):
```
AAEAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGNtYXAAAAAAAAAAAAAAACwAAAAAAAAAAAAAAAAA
AAAAaGVhZAAAAAAAAACsAAAANmhoZWEAAAAAAAAAAAAAACRobXR4AAAAAAAAAAAAAAAAbG9jYQAA
AAAAAAAAAAAAAG1heHAAAAAAAAAACAAAACBuYW1lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Comment by tcl3** [comment]
I can't reproduce this. Likely fixed by  1eae02a01861804d192ed990b24793a028174588
