### ISSUE TITLE
ShellPosix: Assertion error in Parser::parse

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18306]
When fuzzing ShellPosix, we found that the program crashed with an assertion error:

```
FuzzShellPosix: /root/build/serenity/Meta/Lagom/../../AK/Error.h:188: T AK::ErrorOr<AK::RefPtr<Shell::AST::Node>>::release_value_but_fixme_should_propagate_errors() [T = AK::RefPtr<Shell::AST::Node>, E = AK::Error]: Assertion `!is_error()' failed.
```

Here's the stack trace:

```
#5  0x000055555571ff91 in AK::ErrorOr<AK::RefPtr<Shell::AST::Node>, AK::Error>::release_value_but_fixme_should_propagate_errors (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan/FuzzShellPosix)
                       ???: class AK::ErrorOr<AK::RefPtr<Shell::AST::Node>, AK::Error>::release_value_but_fixme_should_propagate_errors(this = (class AK::ErrorOr<AK::RefPtr<Shell::AST::Node>, AK::Error> *)0x155553105ca0) {
                       |||:
                       186:     T release_value_but_fixme_should_propagate_errors()
                       187:     {
                       188:         VERIFY(!is_error());
                       |||:
                       ---: }
                       at /root/build/serenity/Meta/Lagom/../../AK/Error.h:188

#6  0x000055555571ff91 in Shell::Posix::Parser::parse (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan/FuzzShellPosix)
                       132: class Shell::Posix::Parser::parse(this = (class Shell::Posix::Parser *)<optimized out>) {
                       133: {
                       134:     return parse_complete_command().release_value_but_fixme_should_propagate_errors();
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Shell/PosixParser.cpp:134

#7  0x000055555571a56f in LLVMFuzzerTestOneInput (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan/FuzzShellPosix)
                       13: int LLVMFuzzerTestOneInput(data = (const uint8_t *)<optimized out>, size = (size_t)7) {
                       ||:
                       ||: /* Local reference: class AK::StringView source = {m_characters = <optimized out>, m_length = 7}; */
                       ||: /* Local reference: const uint8_t * data = <optimized out>; */
                       ||: /* Local reference: size_t size = 7; */
                       ||: /* Local reference: class Shell::Posix::Parser parser = {m_lexer = {m_lexer = {m_input = {m_characters = 0x1555526f6800 "`\\", m_length = 7}, m_index = 7}, m_state = {buffer = {static inline_capacity = 256, m_buffer = {{... */
                       15:     auto source = StringView(static_cast<unsigned char const*>(data), size);
                       16:     Shell::Posix::Parser parser(source);
                       17:     (void)parser.parse();
                       ||:
                       --: }
                       at /root/build/serenity/Meta/Lagom/Fuzzers/FuzzShellPosix.cpp:17
```

You can reproduce the bug with three characters (backquote, backslash, backquote), or use the base64 encoded input:

```
YFwAYNmdAA==
```

**Comment by tcl3** [comment]
I can't reproduce this. I'm not sure which commit fixed the issue, but it looks similar to oss fuzz issue: [57092](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57092), which is verified fixed.
