### ISSUE TITLE
Js: out-of-memory in parse_binding_pattern

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18309]
When fuzzing FuzzJS, we found that the program has exhausted its resource. For example, with a simple input of `a=a=a=5a=5`, it takes more than 2GB of memory and 10 seconds to complete.

Here's the stack trace:
```
#0  parse_binding_pattern () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:2901
#1  0x000055555696fa75 in synthesize_binding_pattern () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:2282
#2  0x000055555696a316 in parse_assignment_expression () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:2311
#3  0x000055555695534f in parse_secondary_expression () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:2156
#4  0x0000555556943da5 in parse_expression () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:2013
#5  0x0000555556929645 in parse_statement () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:694
#6  0x000055555692bc42 in parse_statement_list () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:2488
#7  0x000055555692a295 in parse_script () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:529
#8  0x0000555556929e6d in parse_program () at /root/build/serenity/Userland/Libraries/LibJS/Parser.cpp:508
#9  0x0000555556ef90fd in parse () at /root/build/serenity/Userland/Libraries/LibJS/Script.cpp:20
#10 0x0000555556817544 in LLVMFuzzerTestOneInput () at /root/build/serenity/Meta/Lagom/Fuzzers/FuzzJs.cpp:23
```

You can also reproduce the bug with base64 encoded input:
```
W2E9YT1hPTVhPTUK
```

**Comment by Hendiadyoin1** [comment]
Decodes to:
```js
[a=a=a=5a=5
```
manually further reduced to
```js
[5a=
```

**Comment by tcl3** [comment]
This issue seems to be related to #17903

Attempting to reproduce this now gives the following error: "[SyntaxError] Numeric literal must not be immediately followed by identifier".

Firefox gives a similar error, so I assume this behavior is correct.
