### ISSUE TITLE
TGA: Assertion failure in TGAImageDecoderPlugin::frame

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18310]
When fuzzing TGALoader, we found that the program crashed with an assertion error:

```
FuzzTGALoader: /root/build/serenity/Meta/Lagom/../../AK/Span.h:211: T &AK::Span<const unsigned char>::at(size_t) [T = const unsigned char]: Assertion `index < this->m_size' failed.
```

Here's the stack trace:
```
#5  0x000055555573ac16 in Gfx::TGAImageDecoderPlugin::frame (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan/FuzzTGALoader)
                       260: class Gfx::TGAImageDecoderPlugin::frame(this = (class Gfx::TGAImageDecoderPlugin *)<optimized out>, index =
(size_t)<optimized out>) {
                       |||: /* Local reference: size_t index = <optimized out>; */
                       |||: /* Local reference: class Gfx::TGAImageDecoderPlugin * this = <optimized out>; */
                       |||:
                       ---: }
                       at /root/build/serenity/Meta/Lagom/../../AK/Span.h:211

#6  0x00005555556b61ff in LLVMFuzzerTestOneInput (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan/FuzzTGALoader)
                       11: int LLVMFuzzerTestOneInput(data = (const uint8_t *)<optimized out>, size = (size_t)<optimized out>) {
                       ||:
                       ||: /* Local reference: class AK::NonnullOwnPtr<Gfx::ImageDecoderPlugin> decoder = {m_ptr = 0x602000000010}; */
                       ||: /* Local reference: class AK::ErrorOr<AK::NonnullOwnPtr<Gfx::ImageDecoderPlugin>, AK::Error> decoder_or_error
 = {m_value_or_error = {<AK::Detail::InheritFromPacks<AK::Detail::IntegerSequence<unsigned int, 0u, 1u>, AK::De... */
                       16:     auto decoder = decoder_or_error.release_value();
                       17:     decoder->initialize();
                       18:     (void)decoder->frame(0);
                       ||:
                       --: }
                       at /root/build/serenity/Meta/Lagom/Fuzzers/FuzzTGALoader.cpp:18
```

You can reproduce the bug with the following base64 encoded input:
```
AAACAAAAAAAAAAAAAAEAICAA
```

**Comment by LucasChollet** [comment]
@hghwnd are you still able to reproduce that locally?

**Comment by supercomputer7** [comment]
https://discord.com/channels/830522505605283862/834851530946773022/1131971366548144219

> [6:30 PM]supercomputer7: I tried to open ImageViewer
> [6:30 PM]supercomputer7: it doesn't crash on this input
> [6:30 PM]supercomputer7: seems irrelevant, could be a bug in the implementation in April

I think we can close this.
