### ISSUE TITLE
VP9Decoder: Assertion failure in parse_color_config

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18320]
When fuzzing VP9Decoder, we found that the program crashed with an assertion error:

```
FuzzVP9Decoder: /root/build/serenity/Userland/Libraries/LibVideo/VP9/Parser.cpp:318: DecoderErrorOr<Video::VP9::ColorConfig> Video::VP9:
:Parser::parse_color_config(AK::BigEndianInputBitStream &, u8): Assertion `false' failed.
```

Here's the stack trace:
```
#5  0x000055555570c36f in parse_color_config (r-xp   /root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzVP9Decoder)
                       ???: void parse_color_config() {
                       |||:
                       316:         } else {
                       317:             // FIXME: Spec does not specify the subsampling value here. Is this an error or should we set a
default?
                       318:             VERIFY_NOT_REACHED();
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibVideo/VP9/Parser.cpp:318

#6  0x0000555555708592 in uncompressed_header (r-xp   /root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzVP9Decoder)
                       ???: void uncompressed_header() {
                       |||:
                       186:         type = FrameType::KeyFrame;
                       187:         TRY(frame_sync_code(frame_context.bit_stream));
                       188:         frame_context.color_config = TRY(parse_color_config(frame_context.bit_stream, frame_context.profile)
);
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibVideo/VP9/Parser.cpp:188

#7  0x0000555555707940 in parse_frame (r-xp   /root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzVP9Decoder)
                       ??: void parse_frame() {
                       ||:
                       90:     //       call to this function, since it will rarely change sizes.
                       91:     FrameContext frame_context { frame_data, m_reusable_frame_block_contexts };
                       92:     TRY(uncompressed_header(frame_context));
                       ||:
                       --: }
                       at /root/build/serenity/Userland/Libraries/LibVideo/VP9/Parser.cpp:92
```

You can reproduce the bug with the following base64 encoded input:
```
k0mDQvc=
```

**Comment by tcl3** [comment]
I can't reproduce this. Likely fixed by 4264b3a1864ace915a885748c060f7a86b3a4e92
