### ISSUE TITLE
VP9Decoder: Assertion failure in Vector2D::index_at

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18321]
When fuzzing VP9Decoder, we found that the program crashed with an assertion error:

```
FuzzVP9Decoder: /root/build/serenity/Userland/Libraries/LibVideo/VP9/ContextStorage.h:134: size_t Video::VP9::Vector2D<Video::VP9::PersistentBlockContext>::index_at(u32, u32) const [T = Video::VP9::PersistentBlockContext]: Assertion `row < height()' failed.
```

Here's the stack trace:
```
#5  0x0000555555719b04 in index_at (r-xp   /root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzVP9Decoder)
                       ???: void index_at() {
                       |||:
                       132:     size_t index_at(u32 row, u32 column) const
                       133:     {
                       134:         VERIFY(row < height());
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibVideo/VP9/ContextStorage.h:134

#6  0x0000555555719b04 in get_segment_id (r-xp   /root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzVP9Decoder)
                       ????: void get_segment_id() {
                       ||||:
                       1108:     for (size_t y = 0; y < ymis; y++) {
                       1109:         for (size_t x = 0; x < xmis; x++) {
                       1110:             segment = min(segment, m_previous_block_contexts.index_at(block_context.row + y, block_context.column + x));
                       ||||:
                       ----: }
                       at /root/build/serenity/Userland/Libraries/LibVideo/VP9/Parser.cpp:1110
```

You can reproduce the bug with the following base64 encoded input:
```
hgAAAAAAAAAAAAABAACHAAAAAAAA
```

**Comment by tcl3** [comment]
I can't reproduce this. I'm not sure which commit fixed it, but it looks similar to oss fuzz issue: [53917](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53917) which is verified fixed.
