### ISSUE TITLE
Ladybird: interia.pl OOM

### ISSUE THREAD

**Issue by kuchikuu** [SerenityOS/serenity#19260]
Browser: Ladybird QT on Arch Linux
Compiled at commit: 0e5ec8c0ab8594602fd226c9b96a64556417445b ( I did git pull recently)
Webpage: https://interia.pl (A Polish website about news, etc)
Date: 2023-06-01 & 2023-06-04 (today)

Type of issue: By loading this website in Ladybird, the system goes out of memory pretty quickly resulting in hanging the entire system (Arch Linux) 

(Last time I checked, Ladybird inside SerenityOS crashes the webpage)

Minimal code that still produces the bug:
extra_mini.html:
```
<!DOCTYPE html>
<html class="" lang="pl">
	<head>
		
		<link href="css.css" media="all" rel="stylesheet" type="text/css">
		
	</head>
	<body data-iwa-block="default" class="sg ">

		<div class="section-wz wz-section no-carousel" id="wz" data-template="no-carousel" data-selector="#wz" data-animationtime="6000" data-color="#005aff" style="--marker-color: #005aff" data-iwa-block="wz-news" data-iwa-viewability-name="wz-news">
			<div class="ad-container wz-halfpage  ">
				<div class="inner-ad" style="max-width: 1372px">
					<div id="ad-view-halfpage_wydarzenia"></div>

					<div id="ad-halfpage_wydarzenia" class="ad " data-iwa-viewability-name="ad-halfpage_wydarzenia" data-ad-sitebranding-ph="true">

					</div>
				</div>
			</div>
			=
		</div>
	</body>
</html>
```
css.css:
```
/* 7b7747ec045ae606eb720a1222f56098-layout.798b93e9.css */
.section-content,.wz-section{
    display:grid;

	justify-content:space-between
}
.content-main,.content-main-wideo{
    display:grid;

    justify-content:space-between
}


/* 7b7747ec045ae606eb720a1222f56098-app.705a7399.css */
.wz-halfpage{
    grid-row:span 2;
    grid-column:-2;
    justify-items:center;
    align-content:center;
    width:100%;
    overflow:unset;
    height:100%
}

```

In general, ```display:grid;``` is what causes the problems. 
When testing Base/res folder, the webpage Base/res/html/misc/display-grid.html crashes.

There's nothing particular I want from this website. It loaded half-way, then ate my ram and hung my system.
I found that interesting and I wanted to prepare a "minimal bug-producting version" so that someone with more knowledge can look at it.

This webpage actually has 2 problems. The first problem is (perhaps?) the CSS, and the second (also CSS-related) hangs the webpage after it's loaded (tested by removing Problem 1 css files) (but I did not focus on this problem though).

I have 30 GB of RAM and the code above is able to fill it in about ~15 seconds.

I have prepared the files for offline debugging:
https://github.com/kuchikuu/ladybird-interia_pl-OOM

**Comment by AtkinsSJ** [comment]
I paused it a few times in gdb, and each time it was on this line in GridFormattingContent: https://github.com/SerenityOS/serenity/blob/89ba00304ce8c022b7cdd47be16759bf8dc008b4/Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp#L565

cc: @kalenikaliaksandr 

<details>
<summary>Example stack trace</summary>

```
#0  0x00007f92cb0769d4 in TemporaryTrack ()
    at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/Layout/GridFormattingContext.h:112
#1  0x00007f92cb076ac0 in try_ensure_capacity () at /home/sam/serenity/Meta/Lagom/../../AK/Vector.h:657
#2  0x00007f92cb06ed82 in try_grow_capacity () at /home/sam/serenity/Meta/Lagom/../../AK/Vector.h:641
#3  try_append () at /home/sam/serenity/Meta/Lagom/../../AK/Vector.h:560
#4  append () at /home/sam/serenity/Meta/Lagom/../../AK/Vector.h:262
#5  initialize_grid_tracks_for_columns_and_rows ()
    at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp:565
#6  0x00007f92cb07505f in run () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp:1374
#7  0x00007f92cb051166 in layout_block_level_box ()
    at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:628
#8  0x00007f92cb04ed0e in operator() () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:683
#9  for_each_child_of_type<Web::Layout::Box, (lambda at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682:49)> () at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:314
#10 for_each_child_of_type<Web::Layout::Box, (lambda at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682:49)> () at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:321
#11 layout_block_level_children () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682
#12 0x00007f92cb0514dc in layout_block_level_box ()
    at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:646
#13 0x00007f92cb04ed0e in operator() () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:683
#14 for_each_child_of_type<Web::Layout::Box, (lambda at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682:49)> () at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:314
#15 for_each_child_of_type<Web::Layout::Box, (lambda at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682:49)> () at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:321
#16 layout_block_level_children () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682
#17 0x00007f92cb04e789 in run () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:70
#18 0x00007f92cb051166 in layout_block_level_box ()
    at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:628
#19 0x00007f92cb04ed0e in operator() () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:683
#20 for_each_child_of_type<Web::Layout::Box, (lambda at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682:49)> () at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:314
#21 for_each_child_of_type<Web::Layout::Box, (lambda at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682:49)> () at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:321
#22 layout_block_level_children () at /home/sam/serenity/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:682
#23 0x00007f92cae3b800 in update_layout () at /home/sam/serenity/Userland/Libraries/LibWeb/DOM/Document.cpp:883
#24 0x00007f92cb0d24a0 in operator() () at /home/sam/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/SafeFunction.h:81
#25 operator() () at /home/sam/serenity/Userland/Libraries/LibWeb/Platform/TimerSerenity.cpp:23
#26 call () at /home/sam/serenity/Meta/Lagom/../../AK/Function.h:173
#27 0x00007f92c8f71776 in operator() () at /home/sam/serenity/Meta/Lagom/../../AK/Function.h:111
#28 timer_event () at /home/sam/serenity/Userland/Libraries/LibCore/Timer.cpp:78
#29 0x00007f92c8f5ba09 in dispatch_event () at /home/sam/serenity/Userland/Libraries/LibCore/Object.cpp:214
#30 0x000055b1cb114b2e in qt_timer_fired () at /home/sam/serenity/Ladybird/EventLoopImplementationQt.cpp:91
#31 operator() () at /home/sam/serenity/Ladybird/EventLoopImplementationQt.cpp:106
#32 call () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:146
#33 call<QtPrivate::List<>, void> () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:256
#34 impl () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:420
#35 0x00007f92c9b61023 in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#36 0x00007f92c9b6f4be in QTimer::timeout(QTimer::QPrivateSignal) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#37 0x00007f92c9b5562f in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#38 0x00007f92c9b08a58 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#39 0x00007f92c9c71203 in QTimerInfoList::activateTimers() () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#40 0x00007f92c9d30bfc in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#41 0x00007f92c75a6d3b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007f92c75fb6c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007f92c75a43e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007f92c9d30f0c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /lib/x86_64-linux-gnu/libQt6Core.so.6
#45 0x000055b1cb114290 in pump () at /home/sam/serenity/Ladybird/EventLoopImplementationQt.cpp:56
--Type <RET> for more, q to quit, c to continue without paging--c
#46 0x00007f92c8f4d33a in pump () at /home/sam/serenity/Userland/Libraries/LibCore/EventLoop.cpp:87
#47 spin_until () at /home/sam/serenity/Userland/Libraries/LibCore/EventLoop.cpp:82
#48 0x00007f92cb0d16f0 in spin_until () at /home/sam/serenity/Userland/Libraries/LibWeb/Platform/EventLoopPluginSerenity.cpp:19
#49 0x00007f92caf4b98d in spin_until () at /home/sam/serenity/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:78
#50 0x00007f92cafc933c in the_end () at /home/sam/serenity/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:302
#51 0x00007f92cafc8f09 in run () at /home/sam/serenity/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:218
#52 0x00007f92cb098105 in load_html () at /home/sam/serenity/Userland/Libraries/LibWeb/Loader/FrameLoader.cpp:162
#53 0x00007f92cb09917e in operator()<AK::Span<const unsigned char>, const AK::HashMap<AK::DeprecatedString, AK::DeprecatedString, AK::CaseInsensitiveStringTraits, AK::Traits<AK::DeprecatedString>, false>, AK::Optional<unsigned int> > () at /home/sam/serenity/Userland/Libraries/LibWeb/Loader/FrameLoader.cpp:188
#54 call () at /home/sam/serenity/Meta/Lagom/../../AK/Function.h:173
#55 0x00007f92cb0a85a0 in operator() () at /home/sam/serenity/Meta/Lagom/../../AK/Function.h:111
#56 0x00007f92cb0a4f9b in operator() () at /home/sam/serenity/Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp:281
#57 call () at /home/sam/serenity/Meta/Lagom/../../AK/Function.h:173
#58 0x000055b1cb097ae1 in operator() () at /home/sam/serenity/Meta/Lagom/../../AK/Function.h:111
#59 0x000055b1cb095769 in handle_file_return () at /home/sam/serenity/Userland/Services/WebContent/ConnectionFromClient.cpp:753
#60 0x000055b1cb098dba in handle () at WebContent/WebContentServerEndpoint.h:4706
#61 0x00007f92c9794180 in handle_messages () at /home/sam/serenity/Userland/Libraries/LibIPC/Connection.cpp:130
#62 0x00007f92c8f70629 in operator() () at /home/sam/serenity/Meta/Lagom/../../AK/Function.h:111
#63 process () at /home/sam/serenity/Userland/Libraries/LibCore/ThreadEventQueue.cpp:113
#64 0x00007f92c9b61023 in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#65 0x00007f92c9b6f4be in QTimer::timeout(QTimer::QPrivateSignal) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#66 0x00007f92c9b5562f in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#67 0x00007f92c9b08a58 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#68 0x00007f92c9c71203 in QTimerInfoList::activateTimers() () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#69 0x00007f92c9d30c44 in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#70 0x00007f92c75a6d3b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#71 0x00007f92c75fb6c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#72 0x00007f92c75a43e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#73 0x00007f92c9d30eae in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#74 0x00007f92c9b15adb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#75 0x00007f92c8f4d220 in exec () at /home/sam/serenity/Userland/Libraries/LibCore/EventLoop.cpp:75
#76 0x000055b1cb121e49 in serenity_main () at /home/sam/serenity/Ladybird/WebContent/main.cpp:93
#77 0x000055b1cb1235c3 in main () at /home/sam/serenity/Userland/Libraries/LibMain/Main.cpp:39
```

</details>

**Comment by kalenikaliaksandr** [comment]
It should been fixed with https://github.com/SerenityOS/serenity/pull/19299. thank you for providing reduced example!
