### ISSUE TITLE
LibWeb: Crash in window.setTimeout() on spotify.com

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#20970]
To reproduce, open https://spotify.com/ and click on the hamburger menu in the top right.

```
VERIFICATION FAILED: initiating_script at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp:222

#0  ak_verification_failed () at /home/kling/src/serenity/AK/Assertions.cpp:72
#1  0x00007fc184ad1bc2 in run_timer_initialization_steps ()
    at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp:222
#2  0x00007fc184ad0fb5 in set_timeout () at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp:173
#3  0x00007fc184fdb055 in operator() ()
    at /home/kling/src/serenity/Build/lagom/Userland/Libraries/LibWeb/Bindings/WindowGlobalMixin.cpp:4659
#4  throw_dom_exception_if_needed<(lambda at /home/kling/src/serenity/Build/lagom/Userland/Libraries/LibWeb/Bindings/WindowGlobalMixin.cpp:4659:36), int, int> () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/Bindings/ExceptionOrUtils.h:110
#5  set_timeout () at /home/kling/src/serenity/Build/lagom/Userland/Libraries/LibWeb/Bindings/WindowGlobalMixin.cpp:4659
#6  0x000055e49dea918d in JS::SafeFunction<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>::CallableWrapper<JS::ThrowCompletionOr<JS::Value> (*)(JS::VM&)>::call(JS::VM&) () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/SafeFunction.h:133
#7  0x00007fc1840f7dc4 in operator() () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/SafeFunction.h:85
#8  call () at /home/kling/src/serenity/Userland/Libraries/LibJS/Runtime/NativeFunction.cpp:222
#9  0x00007fc1840f797a in internal_call () at /home/kling/src/serenity/Userland/Libraries/LibJS/Runtime/NativeFunction.cpp:151
#10 0x00007fc183fbd5f1 in call_impl () at /home/kling/src/serenity/Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp:60
#11 0x00007fc18401f5d1 in call ()
    at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/Runtime/AbstractOperations.h:81
#12 internal_call () at /home/kling/src/serenity/Userland/Libraries/LibJS/Runtime/BoundFunction.cpp:65
#13 0x00007fc183fbdba0 in call_impl () at /home/kling/src/serenity/Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp:73
#14 0x00007fc184c0eef4 in call ()
    at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/Runtime/AbstractOperations.h:103
#15 call_user_object_operation () at /home/kling/src/serenity/Userland/Libraries/LibWeb/WebIDL/AbstractOperations.cpp:175
#16 0x00007fc184927b28 in call_user_object_operation<Web::DOM::Event*&> ()
```

**Comment by Lubrsi** [comment]
Spec Issue: https://github.com/whatwg/html/issues/9633

**Comment by bathos** [comment]
Decidedly off-topic, but: I landed here because I’d reported the spec issue in question and out of curiosity followed the stack trace above to see where this was happending and I just want to say ... this code base is a work of art.
