### ISSUE TITLE
LibWeb: Assertion failure in HTMLTextAreaElement when loading varberg.se

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#20993]
Fails immediately upon load of https://varberg.se/

```
VERIFICATION FAILED: m_ptr at Userland/Libraries/LibJS/Heap/GCPtr.h:168
#0  ak_verification_failed () at /home/kling/src/serenity/AK/Assertions.cpp:72
#1  0x00007f4d93a24157 in operator-> () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/Heap/GCPtr.h:168
#2  children_changed () at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp:123
#3  0x00007f4d9391ebf6 in insert_before () at /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Node.cpp:484
#4  0x00007f4d9391f4de in pre_insert () at /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Node.cpp:506
#5  0x00007f4d93921320 in append_child () at /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Node.cpp:537
#6  operator()<Web::DOM::Node> () at /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Node.cpp:838
#7  for_each_child<(lambda at /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Node.cpp:837:24)> ()
    at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/DOM/Node.h:547
#8  clone_node () at /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Node.cpp:837
...
```

cc @AtkinsSJ

**Comment by awesomekling** [comment]
Same issue on https://twinings.co.uk :catdogalert:
