### ISSUE TITLE
LibWeb: Assertion failure on https://en.wikipedia.org/wiki/2023_Marrakesh-Safi_earthquake

### ISSUE THREAD

**Issue by shannonbooth** [SerenityOS/serenity#21011]
Seems pretty reproducable loading the linked URL and scrolling around a little bit. Happens after a bit of a delay:

GDB backtrace:
```
#0  ak_verification_failed() () at /home/shannon/personal/serenity/AK/Assertions.cpp:72
#1  0x00007f0e283bb591 in resolve_relative_positions() () at /home/shannon/personal/serenity/Meta/Lagom/../../AK/NonnullOwnPtr.h:98
#2  0x00007f0e283bb63d in commit() () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:270
#3  0x00007f0e28184286 in update_layout() () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/DOM/Document.cpp:1010
#4  0x00007f0e281a1c23 in get_bounding_client_rect() () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/DOM/Element.cpp:776
#5  0x00007f0e2818d139 in run_the_update_intersection_observations_steps() () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/DOM/Document.cpp:3221
#6  0x00007f0e2827241d in operator() () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:201
#7  operator()<(lambda at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:200:44)> () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:144
#8  process() () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:200
#9  0x00007f0e28434140 in operator() () at /home/shannon/personal/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/SafeFunction.h:85
#10 operator() () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Platform/TimerSerenity.cpp:23
#11 call() () at /home/shannon/personal/serenity/Meta/Lagom/../../AK/Function.h:174
#12 0x00007f0e2712e289 in operator()() () at /home/shannon/personal/serenity/Meta/Lagom/../../AK/Function.h:107
#13 0x00007f0e2712d805 in dispatch_event() () at /home/shannon/personal/serenity/Userland/Libraries/LibCore/EventReceiver.cpp:163
#14 0x0000560e06a68f7e in qt_timer_fired () at /home/shannon/personal/serenity/Ladybird/Qt/EventLoopImplementationQt.cpp:90
#15 operator() () at /home/shannon/personal/serenity/Ladybird/Qt/EventLoopImplementationQt.cpp:105
#16 call () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:146
#17 call<QtPrivate::List<>, void> () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:256
#18 impl() () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:420
#19 0x00007f0e28cad023 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#20 0x00007f0e28cbb4be in QTimer::timeout(QTimer::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#21 0x00007f0e28ca162f in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#22 0x00007f0e28c54a2d in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#23 0x00007f0e28dbd203 in QTimerInfoList::activateTimers() () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#24 0x00007f0e28e7cc44 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#25 0x00007f0e2685ad3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f0e268b0258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f0e268583e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f0e28e7ceae in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#29 0x00007f0e28c61adb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#30 0x00007f0e27126993 in exec() () at /home/shannon/personal/serenity/Userland/Libraries/LibCore/EventLoop.cpp:86
#31 0x0000560e06a72bda in serenity_main() () at /home/shannon/personal/serenity/Ladybird/WebContent/main.cpp:119
#32 0x0000560e06a74122 in main() () at /home/shannon/personal/serenity/Userland/Libraries/LibMain/Main.cpp:39 
```

**Comment by shannonbooth** [comment]
For some reason I get:

```
VERIFICATION FAILED: i < m_size at /home/shannon/personal/serenity/Meta/Lagom/../../AK/Vector.h:139
/home/shannon/personal/serenity/Build/lagom/lib/liblagom-core.so.0(ak_verification_failed+0x79) [0x7efd9d244149]
/home/shannon/personal/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Layout::LayoutState::resolve_relative_positions(AK::Vector<Web::Painting::PaintableWithLines&, 0ul> const&) 0x3b1) [0x7efd9e4b2591]
```

When running outside of gdb

**Comment by shannonbooth** [comment]
I never found out what the issue was, but I can't reproduce this any more. Will close for now
