### ISSUE TITLE
LibWeb: Crash on bandcamp during `finalize_a_same_document_navigation`

### ISSUE THREAD

**Issue by trflynn89** [SerenityOS/serenity#21355]
For example, on https://xboygeniusx.bandcamp.com/album/the-record:
```
#0  ak_verification_failed () at AK/Assertions.cpp:96
#1  0x00007ffff69b7d67 in AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>::at () at AK/Vector.h:148
#2  AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>::operator[] () at AK/Vector.h:156
#3  AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >::operator* () at AK/Iterator.h:56
#4  AK::find_if<AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::find<AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >(AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> const&)::{lambda(auto:1 const&)#1}>(AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::find<AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >(AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> const&)::{lambda(auto:1 const&)#1}&&) () at AK/Find.h:19
#5  AK::find<AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, AK::SimpleIterator<AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> >, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry> > ()
    at AK/Find.h:29
#6  AK::Vector<JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, 0ul>::find () at AK/Vector.h:787
#7  Web::HTML::finalize_a_same_document_navigation () at Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp:637
#8  0x00007ffff68d7d39 in JS::SafeFunction<void ()>::operator()() const () at Userland/Libraries/LibJS/SafeFunction.h:85
#9  Web::HTML::SessionHistoryTraversalQueue::SessionHistoryTraversalQueue()::{lambda()#1}::operator()() const () at Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.h:21
```

In `finalize_a_same_document_navigation`, when we replace the entry:
```c++
// 1. Replace entryToReplace with targetEntry in targetEntries.
*(target_entries.find(*entry_to_replace)) = target_entry;
```

`target_entries` has one entry with a URL `https://xboygeniusx.bandcamp.com/album/the-record`. And `entry_to_replace` has the same URL, but a different address. So the lookup fails, and we try to dereference a past-the-end iterator.

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/21355">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/21355/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/SerenityOS/serenity/issues/21355/pledge.svg">
</picture>
</a>

**Comment by ADKaster** [comment]
@trflynn89 This doesn't repro on master. Checking if it was 22285 or another PR (possibly my navigables PR?) that fixed it now.

**Comment by kalenikaliaksandr** [comment]
no longer reproducible
