### ISSUE TITLE
LibWeb: SIGFPE in normalized_border_radii_data() on https://blt.se/

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22295]
To reproduce, load https://blt.se/

Backtrace:
```
Thread 1 "WebContent" received signal SIGFPE, Arithmetic exception.
0x00007ff564f7967c in rounding_divide<long> () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/PixelUnits.h:293
293	    if ((dividend < 0) == (divisor < 0))
(gdb) bt
#0  0x00007ff564f7967c in rounding_divide<long> () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/PixelUnits.h:293
#1  operator* () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/PixelUnits.h:375
#2  operator*= () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/PixelUnits.h:224
#3  normalized_border_radii_data () at /home/kling/src/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:257
#4  0x00007ff564f7922f in resolve_border_radii () at /home/kling/src/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:333
#5  0x00007ff564f79e17 in commit () at /home/kling/src/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:434
#6  0x00007ff564d26052 in update_layout () at /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Document.cpp:1031
#7  0x00007ff564526299 in operator() () at /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:115
#8  0x00007ff564525815 in dispatch_event () at /home/kling/src/serenity/Userland/Libraries/LibCore/EventReceiver.cpp:163
#9  0x0000562f116b393e in qt_timer_fired () at /home/kling/src/serenity/Ladybird/Qt/EventLoopImplementationQt.cpp:90
```

cc @kalenikaliaksandr

**Comment by awesomekling** [comment]
This no longer reproduces :)
