### ISSUE TITLE
LibWeb: Crash when reloading after Acid3 finished

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22443]
To reproduce:

1. Open http://wpt.live/acid/acid3/test.html
2. Wait for the test to finish
3. Click the browser reload button.

Backtrace:
```
#3  0x00007efdeef17da0 in ak_verification_failed () at /home/kling/src/serenity/AK/Assertions.cpp:108
#4  0x00007efdf57c12f5 in get_session_history_entries () at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/Navigable.cpp:483
#5  0x00007efdf57bfd2f in get_the_target_history_entry () at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/Navigable.cpp:160
#6  0x00007efdf5a28d3e in get_all_navigables_whose_current_session_history_entry_will_change_or_reload ()
    at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp:225
#7  0x00007efdf5a29fcb in apply_the_history_step () at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp:257
#8  0x00007efdf5a2e11b in update_for_navigable_creation_or_destruction () at /home/kling/src/serenity/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp:543
#9  0x00007efdf4b6a0e4 in operator() () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibJS/SafeFunction.h:85
#10 0x00007efdf5a3bd40 in operator() () at /home/kling/src/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.h:21
#11 call () at /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:182
#12 0x00007efdeee56438 in operator() () at /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:115
#13 0x00007efdeee527cf in dispatch_event () at /home/kling/src/serenity/Userland/Libraries/LibCore/EventReceiver.cpp:163
#14 0x0000560c1aeac9bd in qt_timer_fired () at /home/kling/src/serenity/Ladybird/Qt/EventLoopImplementationQt.cpp:90
#15 operator() () at /home/kling/src/serenity/Ladybird/Qt/EventLoopImplementationQt.cpp:105
#16 call () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:127
#17 call<QtPrivate::List<>, void> () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:241
#18 impl () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:408
#19 0x00007efdf878113e in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#20 0x00007efdf87855ce in QTimer::timeout(QTimer::QPrivateSignal) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#21 0x00007efdf8773856 in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#22 0x00007efdf8736975 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#23 0x00007efdf8870e69 in QTimerInfoList::activateTimers() () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#24 0x00007efdf89266f4 in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#25 0x00007efdee713b2c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007efdee76f46f in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007efdee711d20 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007efdf8924420 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#29 0x00007efdf8740cea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#30 0x00007efdeee32c72 in exec () at /home/kling/src/serenity/Userland/Libraries/LibCore/EventLoop.cpp:86
#31 0x0000560c1aee5f0a in serenity_main () at /home/kling/src/serenity/Ladybird/WebContent/main.cpp:136
#32 0x0000560c1aef1f4e in main () at /home/kling/src/serenity/Userland/Libraries/LibMain/Main.cpp:39
```

**Comment by awesomekling** [comment]
This no longer happens.
