### ISSUE TITLE
LibWeb: Regression, immediate crash on https://null.com/

### ISSUE THREAD

**Issue by kalenikaliaksandr** [SerenityOS/serenity#23424]
```
  * frame #0: 0x00000001075e0958 liblagom-web.0.dylib`::layout_node() [inlined] operator Web::Layout::Node * at GCPtr.h:183:34 [opt]
    frame #1: 0x00000001075e0958 liblagom-web.0.dylib`::layout_node() [inlined] layout_node at Node.h:196:42 [opt]
    frame #2: 0x00000001075e0958 liblagom-web.0.dylib`::layout_node() at Element.cpp:2103:54 [opt]
    frame #3: 0x000000010757df64 liblagom-web.0.dylib`::operator()() at StyleComputer.cpp:807:40 [opt]
    frame #4: 0x000000010757d4dc liblagom-web.0.dylib`::operator()() at StyleComputer.cpp:825:35 [opt]
    frame #5: 0x0000000107573dc8 liblagom-web.0.dylib`::collect_animation_into() [inlined] interpolate_transform at StyleComputer.cpp:1049:24 [opt]
    frame #6: 0x0000000107573db8 liblagom-web.0.dylib`::collect_animation_into() [inlined] interpolate_property at StyleComputer.cpp:1162:20 [opt]
    frame #7: 0x0000000107573da8 liblagom-web.0.dylib`::collect_animation_into() at StyleComputer.cpp:1256:27 [opt]
    frame #8: 0x00000001075756ac liblagom-web.0.dylib`::compute_cascaded_values() at StyleComputer.cpp:1439:17 [opt]
    frame #9: 0x000000010757ad20 liblagom-web.0.dylib`::compute_style_impl() at StyleComputer.cpp:2150:5 [opt]
    frame #10: 0x000000010757aa28 liblagom-web.0.dylib`::compute_style() at StyleComputer.cpp:2120:18 [opt]
    frame #11: 0x00000001075e056c liblagom-web.0.dylib`::recompute_style() at Element.cpp:576:36 [opt]
    frame #12: 0x00000001075c4680 liblagom-web.0.dylib`::update_style_recursively() at Document.cpp:1125:53 [opt]
    frame #13: 0x00000001075c4784 liblagom-web.0.dylib`::update_style_recursively() [inlined] operator()<Web::DOM::Node> at Document.cpp:1143:45 [opt]
    frame #14: 0x00000001075c4768 liblagom-web.0.dylib`::update_style_recursively() [inlined] for_each_child<(lambda at /Users/kalenik/projects/serenity/Userland/Libraries/LibWeb/DOM/Document.cpp:1141:29)> at Node.h:557:13 [opt]
    frame #15: 0x00000001075c4760 liblagom-web.0.dylib`::update_style_recursively() at Document.cpp:1141:14 [opt]
    frame #16: 0x00000001075c4784 liblagom-web.0.dylib`::update_style_recursively() [inlined] operator()<Web::DOM::Node> at Document.cpp:1143:45 [opt]
```

@mattco98

**Comment by awesomekling** [comment]
ASAN says:
```
/home/kling/src/serenity/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:1256:27: runtime error: reference binding to null pointer of type 'DOM::Element'
    #0 0x7fcd2c20c259 in Web::CSS::StyleComputer::collect_animation_into(JS::NonnullGCPtr<Web::Animations::KeyframeEffect>, Web::CSS::StyleProperties&) const /home/kling/src/serenity/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:1256:27
    #1 0x7fcd2c2140ae in Web::CSS::StyleComputer::compute_cascaded_values(Web::CSS::StyleProperties&, Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>, bool&, Web::CSS::StyleComputer::ComputeStyleMode) const /home/kling/src/serenity/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:1439:17
    #2 0x7fcd2c234811 in Web::CSS::StyleComputer::compute_style_impl(Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>, Web::CSS::StyleComputer::ComputeStyleMode) const /home/kling/src/serenity/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:2150:5
    #3 0x7fcd2c233053 in Web::CSS::StyleComputer::compute_style(Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>) const /home/kling/src/serenity/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:2120:18
    #4 0x7fcd2c4c7df7 in Web::DOM::Element::recompute_style() /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Element.cpp:576:36
    #5 0x7fcd2c3fd7ac in Web::DOM::update_style_recursively(Web::DOM::Node&) /home/kling/src/serenity/Userland/Libraries/LibWeb/DOM/Document.cpp:1125:53
```
