### ISSUE TITLE
Ladybird: JS Error at "https://turbowarp.org/"

### ISSUE THREAD

**Issue by mguinhos** [SerenityOS/serenity#23749]
![Screenshot](https://github.com/SerenityOS/serenity/assets/43307018/56d417fd-82f9-4d9a-bdbf-3c142c8244f3)

# Logs (From outside vm)
```
104.340 WebWorker(63): DedicatedWorkerHost: Unable to fetch script blob:https://turbowarp.org/8eddddce-42e1-4a91-9911-61c98c34e325 because script was null
104.352 RequestServer(64): Loaded 145 of 145 (100%) provided CA Certificates
104.627 WebContent(60): (js error) [TypeError] undefined is not a function (evaluated from 'e.createBuffer')
104.631 WebContent(60): (js error) "gui" "error" "Unhandled Error with action='Top Level App': TypeError: undefined is not a function (evaluated from 'e.createBuffer')\n    at https://turbowarp.org/js/vendors~editor~embed~fullscreen~player.e000f499234de2af2125.js:2:426404\n    at u (https://turbowarp.org/js/vendors~editor~embed~fullscreen~player.e000f499234de2af2125.js:2:426404)\n    at https://turbowarp.org/js/vendors~editor~embed~fullscreen~player.e000f499234de2af2125.js:2:427591\n    at <unknown>\n    at f (https://turbowarp.org/js/vendors~editor~embed~fullscreen~player.e000f499234de2af2125.js:2:427119)\n    at https://turbowarp.org/js/vendors~editor~embed~fullscreen~player.e000f499234de2af2125.js:2:424879\n    at _createGeometry (https://turbowarp.org/js/vendors~editor~embed~fullscreen~player.e000f499234de2af2125.js:2:5065684)\n    at _ (https://turbowarp.org/js/vendors~editor~embed~fullscreen~player.e000f499234de2af2125.js:2:5046356)\n    at Lg (https://turbowarp.org/js/editor~embed~fullscreen~player.d1d3a62dfc29a66aab33.js:1:480020)\n    at Tl (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:54353)\n    at Vi (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:71766)\n    at Sa (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:109872)\n    at _u (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:101354)\n    at Tu (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:101279)\n    at vu (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:98312)\n    at fu (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:95056)\n    at Zu (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:116281)\n    at https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:117490\n    at gu (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:98661)\n    at lc (https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:117475)\n    at https://turbowarp.org/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.0b6908cbbcd0c8aead19.js:2:120475\n    at https://turbowarp.org/js/editor~embed~fullscreen~player.d1d3a62dfc29a66aab33.js:1:59499\n    at https://turbowarp.org/js/player.6a62b0669de48284beee.js:1:7730\n    at <unknown>\n    at i (https://turbowarp.org/js/player.6a62b0669de48284beee.js:1:573)\n    at n (https://turbowarp.org/js/player.6a62b0669de48284beee.js:1:438)\n    at https://turbowarp.org/js/player.6a62b0669de48284beee.js:1:6936\n    at https://turbowarp.org/js/player.6a62b0669de48284beee.js:1:6939\n\nComponent stack: \n    in Lg\n    in Connect(Lg)\n    in div\n    in w\n    in div\n    in w\n    in Xg\n    in $g\n    in MediaQuery\n    in rI\n    in Connect(rI)\n    in InjectIntl(Connect(rI))\n    in II\n    in Connect(II)\n    in InjectIntl(Connect(II))\n    in t\n    in Connect(t)\n    in t\n    in Connect(t)\n    in InjectIntl(Connect(t))\n    in t\n    in Connect(t)\n    in t\n    in Connect(t)\n    in t\n    in Connect(t)\n    in t\n    in Connect(t)\n    in InjectIntl(Connect(t))\n    in t\n    in Connect(t)\n    in InjectIntl(Connect(t))\n    in t\n    in Connect(t)\n    in t\n    in Connect(t)\n    in t\n    in Connect(t)\n    in c\n    in Unknown\n    in IntlProvider\n    in Connect(IntlProvider)\n    in t\n    in Connect(t)\n    in Unknown\n    in div\n    in div\n    in Le\n    in Connect(Le)\n    in InjectIntl(Connect(Le))\n    in t\n    in Connect(t)\n    in t\n    in Connect(t)\n    in InjectIntl(Connect(t))\n    in t\n    in Connect(t)\n    in c\n    in Unknown\n    in IntlProvider\n    in Connect(IntlProvider)\n    in r\n    in a"
104.737 WebContent(60): Can't keep up! Skipping approximately 71 iteration(s) of a reloading timer (delayed by 1130ms).
104.737 WebContent(60): Can't keep up! Skipping approximately 54 iteration(s) of a reloading timer (delayed by 53ms).
104.784 WebContent(60): Can't keep up! Skipping approximately 2 iteration(s) of a reloading timer (delayed by 16ms).
104.807 WebContent(60): Potential FIXME: Creating unknown generic element 'desc' in namespace 'http://www.w3.org/2000/svg'
104.929 WebContent(60): Can't keep up! Skipping approximately 1 iteration(s) of a reloading timer (delayed by 15ms).
104.949 WebContent(60): Potential FIXME: Creating unknown generic element 'desc' in namespace 'http://www.w3.org/2000/svg'
105.129 WebContent(60): Can't keep up! Skipping approximately 3 iteration(s) of a reloading timer (delayed by 41ms).
105.149 WebContent(60): Potential FIXME: Creating unknown generic element 'desc' in namespace 'http://www.w3.org/2000/svg'
105.220 WebContent(60): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
105.986 WebContent(60): Potential FIXME: Creating unknown generic element 'desc' in namespace 'http://www.w3.org/2000/svg'
105.990 WebContent(60): Can't keep up! Skipping approximately 1 iteration(s) of a reloading timer (delayed by 13ms).
106.328 WebContent(60): Potential FIXME: Creating unknown generic element 'desc' in namespace 'http://www.w3.org/2000/svg'
```

**Comment by ADKaster** [comment]
Any ideas looking at the JS from the site as to what type `e` and `a` are supposed to be and what `createBuffer` method it's trying to call? It would be much more actionable if we knew which Web API we are missing.

**Comment by mattco98** [comment]
> Any ideas looking at the JS from the site as to what type e and a are supposed to be and what createBuffer method it's trying to call? It would be much more actionable if we knew which Web API we are missing.

Seems to be [WebGLRenderingContext](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/createBuffer#specifications):

![Capture](https://github.com/SerenityOS/serenity/assets/28801118/5a3b5c66-d200-4202-b4c7-ac1ab05bb042)

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
