### ISSUE TITLE
Crash on nytimes.com due to stacking context painted twice

### ISSUE THREAD

**Issue by shannonbooth** [SerenityOS/serenity#24197]
Can be seen just by loading nytimes.com

Interesting, this crashes the entire browser, not just the tab.

Backtrace:
```
ak_verification_failed () at /home/shannon/personal/serenity/AK/Assertions.cpp:108
108         __builtin_trap();
(gdb) bt
#0  ak_verification_failed () at /home/shannon/personal/serenity/AK/Assertions.cpp:108
#1  0x00007f0e64931a3b in set_last_paint_generation_id () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Painting/StackingContext.cpp:60
#2  paint_child () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Painting/StackingContext.cpp:179
#3  0x00007f0e64933f3b in for_each_child<(lambda at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Painting/StackingContext.cpp:99:30)> ()
    at /home/shannon/personal/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:228
#4  for_each_child<(lambda at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Painting/StackingContext.cpp:99:30)> ()
    at /home/shannon/personal/serenity/Meta/Lagom/../../Userland/Libraries/LibWeb/TreeNode.h:221
#5  paint_descendants () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Painting/StackingContext.cpp:99
#6  operator()<Web::Painting::Paintable> () at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Painting/StackingContext.cpp:164
#7  0x00007f0e64933f3b in for_each_child<(lambda at /home/shannon/personal/serenity/Userland/Libraries/LibWeb/Painting/StackingContext.cpp:99:30)> ()
```

**Comment by kuchikuu** [comment]
Perhaps interia.pl also suffers from the same crash so I'm going to comment here.

I checked interia.pl:

```
aede0100960b6b9cacd0e5a0bd0887bd34651e29 - crash (Thu May 2 22:32:44 2024 +1200)
b1b7e2324ad52908ab8e49826327c975996c06bf - crash (Sun Apr 28 12:19:19 2024 +1200)
.
.
.
8893836b60d5209a7223161c16f6ae668a2e5d91 - no crash (Sun Mar 3 12:49:03 2024 -0800)
```

nytimes.com:

`8893836b60d5209a7223161c16f6ae668a2e5d91 - no crash  (Sun Mar 3 12:49:03 2024 -0800)`

https://newrelic.com/:
`8893836b60d5209a7223161c16f6ae668a2e5d91 - crash  (Sun Mar 3 12:49:03 2024 -0800)`



So between Mar 3 and Apr 28 something happened that crashes the webpages.
I'm going to focus on interia.pl and nytimes.com

I'm slowly going to move up from Mar 3's commit and see where it happens.
(It may take some time)
(I've put the commits in a code block so that this issue won't get mentioned there until I find the commit that breaks the pages.

**Comment by nico** [comment]
#24226 turned this into a dbgln() probably.

**Comment by shannonbooth** [comment]
> #24226 turned this into a dbgln() probably.

Yup crash for this reason is gone. nytimes.com is still crashing, but looks to be for an unrelated problem which I can't seem to get a backtrace for. I'll adjust this issue to just track the stacking contexts issue, and will raise another issue for the crash in nytimes
