### ISSUE TITLE
LibJS: addition_would_overflow assertion failure whilst JSON stringifying

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3458]
Found while fuzzing. Fuzzed programs passed the parser with no errors.

Program 1:
Crash file: [crash-edf33b44077d091845ad8123d7bd1cec77e7b907.txt](https://github.com/SerenityOS/serenity/files/5212144/crash-edf33b44077d091845ad8123d7bd1cec77e7b907.txt)
Expected: ```ov is not defined```
Actual: ```Assertion failed: !Checked<uintptr_t>::addition_would_overflow((uintptr_t)characters, length)```

GDB trace (from interpreter run):
```
#4  0x00000000004f58f4 in AK::StringView::StringView (this=<optimized out>, characters=0x6500d0 "\\u%#08x", length=18446744073709551591) at .././AK/StringView.h:45
#5  AK::StringBuilder::append (this=<optimized out>, characters=0x6500d0 "\\u%#08x", length=18446744073709551591) at ../AK/StringBuilder.cpp:59
#6  0x000000000056066e in JS::JSONObject::quote_json_string (string=...) at ../Libraries/LibJS/Runtime/JSONObject.cpp:374
#7  0x000000000055f9a2 in JS::JSONObject::serialize_json_property (interpreter=..., state=..., key=..., holder=0x113b1f8) at ../Libraries/LibJS/Runtime/JSONObject.cpp:181
#8  0x000000000055d7e3 in JS::JSONObject::stringify_impl (interpreter=..., global_object=..., value=..., replacer=..., space=...) at ../Libraries/LibJS/Runtime/JSONObject.cpp:125
#9  0x000000000055c554 in JS::JSONObject::stringify (interpreter=..., global_object=...) at ../Libraries/LibJS/Runtime/JSONObject.cpp:143
#10 0x00000000004ef02f in AK::Function<JS::Value (JS::Interpreter&, JS::GlobalObject&)>::CallableWrapper<JS::Value (*)(JS::Interpreter&, JS::GlobalObject&)>::call(JS::Interpreter&, JS::GlobalObject&) const (this=<optimized out>, in=..., in=...) at .././AK/Function.h:101
#11 0x000000000050c34f in JS::Interpreter::call_internal (this=0x10a8ea0, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.cpp:263
#12 0x00000000005d836e in JS::Interpreter::call<JS::MarkedValueList> (this=0x10a8ea0, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.h:261
#13 JS::CallExpression::execute (this=<optimized out>, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:198
#14 0x00000000005ddb3a in JS::BinaryExpression::execute (this=0x10a8cf0, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:450
#15 0x0000000000507be2 in JS::Interpreter::run (this=<optimized out>, global_object=..., statement=..., arguments=..., scope_type=<optimized out>) at ../Libraries/LibJS/Interpreter.cpp:88
#16 0x000000000059ac5f in JS::ScriptFunction::call (this=<optimized out>, interpreter=...) at ../Libraries/LibJS/Runtime/ScriptFunction.cpp:133
#17 0x000000000050c34f in JS::Interpreter::call_internal (this=0x10a8ea0, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.cpp:263
#18 0x00000000006087ed in JS::Interpreter::call<JS::MarkedValueList> (this=0x10a8ea0, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.h:261
#19 JS::Interpreter::call<JS::Value, JS::Value, JS::Object*> (this=0x10a8ea0, function=..., this_value=..., args=0x1139198, args=0x1139198, args=0x1139198) at ../Libraries/LibJS/Interpreter.h:95
#20 JS::for_each_item(JS::Interpreter&, JS::GlobalObject&, AK::String const&, AK::Function<AK::IterationDecision (unsigned long, JS::Value, JS::Value)>, bool) (interpreter=..., global_object=..., name=..., callback=..., skip_empty=<optimized out>)
    at ../Libraries/LibJS/Runtime/ArrayPrototype.cpp:138
#21 0x00000000005fecb4 in JS::ArrayPrototype::for_each (interpreter=..., global_object=...) at ../Libraries/LibJS/Runtime/ArrayPrototype.cpp:160
#22 0x00000000004ef02f in AK::Function<JS::Value (JS::Interpreter&, JS::GlobalObject&)>::CallableWrapper<JS::Value (*)(JS::Interpreter&, JS::GlobalObject&)>::call(JS::Interpreter&, JS::GlobalObject&) const (this=<optimized out>, in=..., in=...) at .././AK/Function.h:101
#23 0x000000000050c34f in JS::Interpreter::call_internal (this=0x10a8ea0, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.cpp:263
#24 0x00000000005d836e in JS::Interpreter::call<JS::MarkedValueList> (this=0x10a8ea0, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.h:261
#25 JS::CallExpression::execute (this=<optimized out>, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:198
#26 0x0000000000507be2 in JS::Interpreter::run (this=<optimized out>, global_object=..., statement=..., arguments=..., scope_type=<optimized out>) at ../Libraries/LibJS/Interpreter.cpp:88
```

Program 2:
Crash file: [crash-0e2d6bb1aa81a3905c34909f1f86103de99f4e44.txt](https://github.com/SerenityOS/serenity/files/5212145/crash-0e2d6bb1aa81a3905c34909f1f86103de99f4e44.txt)
Expected: No output
Actual: ```Assertion failed: !Checked<uintptr_t>::addition_would_overflow((uintptr_t)characters, length)```

GDB trace (from interpreter run):
```
#4  0x00000000004f58f4 in AK::StringView::StringView (this=<optimized out>, characters=0x6500d0 "\\u%#08x", length=18446744073709551506) at .././AK/StringView.h:45
#5  AK::StringBuilder::append (this=<optimized out>, characters=0x6500d0 "\\u%#08x", length=18446744073709551506) at ../AK/StringBuilder.cpp:59
#6  0x000000000056066e in JS::JSONObject::quote_json_string (string=...) at ../Libraries/LibJS/Runtime/JSONObject.cpp:374
#7  0x000000000055f9a2 in JS::JSONObject::serialize_json_property (interpreter=..., state=..., key=..., holder=0x1141e78) at ../Libraries/LibJS/Runtime/JSONObject.cpp:181
#8  0x000000000055d7e3 in JS::JSONObject::stringify_impl (interpreter=..., global_object=..., value=..., replacer=..., space=...) at ../Libraries/LibJS/Runtime/JSONObject.cpp:125
#9  0x000000000055c554 in JS::JSONObject::stringify (interpreter=..., global_object=...) at ../Libraries/LibJS/Runtime/JSONObject.cpp:143
#10 0x00000000004ef02f in AK::Function<JS::Value (JS::Interpreter&, JS::GlobalObject&)>::CallableWrapper<JS::Value (*)(JS::Interpreter&, JS::GlobalObject&)>::call(JS::Interpreter&, JS::GlobalObject&) const (this=<optimized out>, in=..., in=...) at .././AK/Function.h:101
#11 0x000000000050c34f in JS::Interpreter::call_internal (this=0x10a9a00, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.cpp:263
#12 0x00000000005d836e in JS::Interpreter::call<JS::MarkedValueList> (this=0x10a9a00, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.h:261
#13 JS::CallExpression::execute (this=<optimized out>, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:198
#14 0x00000000005ddb3a in JS::BinaryExpression::execute (this=0x10a9850, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:450
#15 0x0000000000507be2 in JS::Interpreter::run (this=<optimized out>, global_object=..., statement=..., arguments=..., scope_type=<optimized out>) at ../Libraries/LibJS/Interpreter.cpp:88
#16 0x000000000059ac5f in JS::ScriptFunction::call (this=<optimized out>, interpreter=...) at ../Libraries/LibJS/Runtime/ScriptFunction.cpp:133
#17 0x000000000050c34f in JS::Interpreter::call_internal (this=0x10a9a00, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.cpp:263
#18 0x00000000006087ed in JS::Interpreter::call<JS::MarkedValueList> (this=0x10a9a00, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.h:261
#19 JS::Interpreter::call<JS::Value, JS::Value, JS::Object*> (this=0x10a9a00, function=..., this_value=..., args=0x1139198, args=0x1139198, args=0x1139198) at ../Libraries/LibJS/Interpreter.h:95
#20 JS::for_each_item(JS::Interpreter&, JS::GlobalObject&, AK::String const&, AK::Function<AK::IterationDecision (unsigned long, JS::Value, JS::Value)>, bool) (interpreter=..., global_object=..., name=..., callback=..., skip_empty=<optimized out>)
    at ../Libraries/LibJS/Runtime/ArrayPrototype.cpp:138
#21 0x00000000005fecb4 in JS::ArrayPrototype::for_each (interpreter=..., global_object=...) at ../Libraries/LibJS/Runtime/ArrayPrototype.cpp:160
#22 0x00000000004ef02f in AK::Function<JS::Value (JS::Interpreter&, JS::GlobalObject&)>::CallableWrapper<JS::Value (*)(JS::Interpreter&, JS::GlobalObject&)>::call(JS::Interpreter&, JS::GlobalObject&) const (this=<optimized out>, in=..., in=...) at .././AK/Function.h:101
#23 0x000000000050c34f in JS::Interpreter::call_internal (this=0x10a9a00, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.cpp:263
#24 0x00000000005d836e in JS::Interpreter::call<JS::MarkedValueList> (this=0x10a9a00, function=..., this_value=..., arguments=...) at ../Libraries/LibJS/Interpreter.h:261
#25 JS::CallExpression::execute (this=<optimized out>, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:198
#26 0x0000000000507be2 in JS::Interpreter::run (this=<optimized out>, global_object=..., statement=..., arguments=..., scope_type=<optimized out>) at ../Libraries/LibJS/Interpreter.cpp:88
```

**Comment by linusg** [comment]
Much simpler repro:

```js
JSON.stringify("ç")
```

**Comment by linusg** [comment]
The result isn't quite correct, but it no longer crashes:

```js
> JSON.stringify("ç")
""\u-003d\u-0059""
> JSON.parse(JSON.stringify("ç"))
"?d?9"
```
