### ISSUE TITLE
LibJS: Endless recursion in update_function_name

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3471]
Found while fuzzing.
File: [crash-endless-recursion.txt](https://github.com/SerenityOS/serenity/files/5213316/crash-endless-recursion.txt)

GDB trace:
```
#0  0x00007ffff7ae4fce in _int_malloc (av=av@entry=0x7ffff7c35b80 <main_arena>, bytes=bytes@entry=696) at malloc.c:3679
#1  0x00007ffff7ae7419 in __GI___libc_malloc (bytes=696) at malloc.c:3066
#2  0x0000000000628227 in AK::Vector<JS::ValueAndAttributes, 0ul>::ensure_capacity (this=0x7fffff7ff138, needed_capacity=29) at .././AK/Vector.h:450
#3  AK::Vector<JS::ValueAndAttributes, 0ul>::grow_capacity (this=0x7fffff7ff138, needed_capacity=20) at .././AK/Vector.h:442
#4  AK::Vector<JS::ValueAndAttributes, 0ul>::append (this=0x7fffff7ff138, value=...) at .././AK/Vector.h:386
#5  JS::IndexedProperties::values_unordered (this=<optimized out>) at ../Libraries/LibJS/Runtime/IndexedProperties.cpp:363
#6  0x00000000005df76b in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:63
...
#104732 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104733 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104734 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104735 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104736 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104737 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104738 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104739 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104740 0x00000000005df79f in JS::update_function_name (value=..., name=...) at ../Libraries/LibJS/AST.cpp:64
#104741 0x00000000005e3087 in JS::AssignmentExpression::execute (this=<optimized out>, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:1275
#104742 0x00000000005062a2 in JS::Interpreter::execute_statement (this=<optimized out>, global_object=..., statement=..., arguments=..., scope_type=<optimized out>) at ../Libraries/LibJS/Interpreter.cpp:91
#104743 0x00000000005d4d80 in JS::ScopeNode::execute (this=0x2c0, interpreter=..., global_object=...) at ../Libraries/LibJS/AST.cpp:79
#104744 0x0000000000505d48 in JS::Interpreter::run (this=0x1463e20, global_object=..., program=...) at ../Libraries/LibJS/Interpreter.cpp:76
#104745 0x00000000004ebe02 in LLVMFuzzerTestOneInput (data=<optimized out>, size=<optimized out>) at ../Meta/Lagom/Fuzzers/FuzzJs.cpp:70
#104746 0x000000000047cda2 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) ()
#104747 0x000000000047c4e6 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) ()
#104748 0x000000000047e788 in fuzzer::Fuzzer::MutateAndTestOne() ()
#104749 0x000000000047f486 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) ()
#104750 0x000000000046de3f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) ()
#104751 0x0000000000496c83 in main ()
```

**Comment by Lubrsi** [comment]
Simplified repro:
```js
let bad2 = [];
bad2[5]= [[[bad2]]];
bad2[5] = [[[bad2]]];
```

**Comment by stelar7** [comment]
I suspect this might be an issue again due to https://github.com/SerenityOS/serenity/commit/dc8817638ecc30b8a5ede041327f903671374aa5 :^)

**Comment by thomas-mangin** [comment]
@awesomekling you decided to remove this check .. perhaps something to review.

**Comment by linusg** [comment]
No, this still fine. :)

**Comment by thomas-mangin** [comment]
To be clear, removing the check is not the issue, it was the removing of the map which my now lead to infinite loop for some code. But this is a code review based on searching today YouTube video and no more investigation. So if you guys are happy, I will just take this as a misunderstanding of my side.

**Comment by linusg** [comment]
the infinite loop can be caused by an array containing itself, but since only `ScriptFunction`s are updated now, that can't happen anymore, hence why the hashmap keeping track of visited objects was removed as well.

**Comment by thomas-mangin** [comment]
Understood, thank you for taking the time to explain why.
