### ISSUE TITLE
LibGfx: Vector OOB in PPMLoader::read_pixel_data

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3820]
Found while fuzzing.

PPM:
[crash-7572cdf42583a8ec3b929d9d56e86b13c79b7f79.txt](https://github.com/SerenityOS/serenity/files/5425915/crash-7572cdf42583a8ec3b929d9d56e86b13c79b7f79.txt)
I've had to make the extension .txt to upload it.

Line:
https://github.com/SerenityOS/serenity/blob/a316ca0e0df40f9d08c566fc212517a9c54fb22e/Libraries/LibGfx/PPMLoader.cpp#L311

Trace:
```
FuzzPPM: .././AK/Vector.h:200: T &AK::Vector<Gfx::Color, 0>::at(size_t) [T = Gfx::Color, inline_capacity = 0]: Assertion `i < m_size' failed.
==37345== ERROR: libFuzzer: deadly signal
    #0 0x4cd380 in __sanitizer_print_stack_trace (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x4cd380)
    #1 0x479688 in fuzzer::PrintStackTrace() (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x479688)
    #2 0x45e7d3 in fuzzer::Fuzzer::CrashCallback() (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x45e7d3)
    #3 0x7fe390b993bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)
    #4 0x7fe3909aa18a in __libc_signal_restore_set /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #5 0x7fe3909aa18a in raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #6 0x7fe390989858 in abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:79:7
    #7 0x7fe390989728 in __assert_fail_base /build/glibc-ZN95T4/glibc-2.31/assert/assert.c:92:3
    #8 0x7fe39099af35 in __assert_fail /build/glibc-ZN95T4/glibc-2.31/assert/assert.c:101:3
    #9 0x4f56cc in AK::Vector<Gfx::Color, 0ul>::at(unsigned long) /home/lukew/Desktop/serenity-project/serenity/build/.././AK/Vector.h:200:9
    #10 0x4f56cc in Gfx::read_image_data(Gfx::PPMLoadingContext&, Gfx::Streamer&) /home/lukew/Desktop/serenity-project/serenity/build/../Libraries/LibGfx/PPMLoader.cpp:311:56
    #11 0x4f56cc in Gfx::decode_ppm(Gfx::PPMLoadingContext&) /home/lukew/Desktop/serenity-project/serenity/build/../Libraries/LibGfx/PPMLoader.cpp:351:10
    #12 0x4f5884 in Gfx::PPMImageDecoderPlugin::bitmap() /home/lukew/Desktop/serenity-project/serenity/build/../Libraries/LibGfx/PPMLoader.cpp:422:24
    #13 0x4ceb70 in LLVMFuzzerTestOneInput /home/lukew/Desktop/serenity-project/serenity/build/../Meta/Lagom/Fuzzers/FuzzPPM.cpp:33:26
    #14 0x45fe91 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x45fe91)
    #15 0x45f5d5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x45f5d5)
    #16 0x461877 in fuzzer::Fuzzer::MutateAndTestOne() (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x461877)
    #17 0x462575 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x462575)
    #18 0x450f2e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x450f2e)
    #19 0x479d72 in main (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x479d72)
    #20 0x7fe39098b0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16
    #21 0x425ccd in _start (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzPPM+0x425ccd)
```

**Comment by awesomekling** [comment]
cc @asliturk
