### ISSUE TITLE
LibCompress: !has_any_error() assertion failure in Gzip decompression

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5838]
On latest master.

File: [crash-feac509a3f91fdb4bcdc5da73a4274b8a22e3b07.txt](https://github.com/SerenityOS/serenity/files/6152629/crash-feac509a3f91fdb4bcdc5da73a4274b8a22e3b07.txt) (with txt extension to allow uploading to GH)

Trace:
```
FuzzGzipDecompression: .././AK/Stream.h:40: virtual AK::Detail::Stream::~Stream(): Assertion `!has_any_error()' failed.
==44484== ERROR: libFuzzer: deadly signal
    #0 0x539db1 in __sanitizer_print_stack_trace (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x539db1)
    #1 0x484f08 in fuzzer::PrintStackTrace() (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x484f08)
    #2 0x46a053 in fuzzer::Fuzzer::CrashCallback() (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x46a053)
    #3 0x7f9c27c8e3bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)
    #4 0x7f9c27a9f18a in __libc_signal_restore_set /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #5 0x7f9c27a9f18a in raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #6 0x7f9c27a7e858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
    #7 0x7f9c27a7e728 in __assert_fail_base /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:92:3
    #8 0x7f9c27a8ff35 in __assert_fail /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:101:3
    #9 0x571e55 in AK::Detail::Stream::~Stream() /home/lukew/Desktop/serenity-project/serenity/build/.././AK/Stream.h:40:25
    #10 0x5db3db in AK::CircularDuplexStream<32768ul>::~CircularDuplexStream() /home/lukew/Desktop/serenity-project/serenity/build/.././AK/CircularDuplexStream.h:37:7
    #11 0x5db3db in Compress::DeflateDecompressor::~DeflateDecompressor() /home/lukew/Desktop/serenity-project/serenity/build/../Userland/Libraries/LibCompress/Deflate.cpp:218:1
    #12 0x5db941 in Compress::DeflateDecompressor::~DeflateDecompressor() /home/lukew/Desktop/serenity-project/serenity/build/../Userland/Libraries/LibCompress/Deflate.cpp:213:1
    #13 0x565faa in Compress::GzipDecompressor::Member::~Member() /home/lukew/Desktop/serenity-project/serenity/build/../Userland/Libraries/LibCompress/Gzip.h:76:11
    #14 0x565faa in AK::Optional<Compress::GzipDecompressor::Member>::clear() /home/lukew/Desktop/serenity-project/serenity/build/.././AK/Optional.h:114:22
    #15 0x565faa in Compress::GzipDecompressor::~GzipDecompressor() /home/lukew/Desktop/serenity-project/serenity/build/../Userland/Libraries/LibCompress/Gzip.cpp:67:22
    #16 0x56c8f3 in Compress::GzipDecompressor::~GzipDecompressor() /home/lukew/Desktop/serenity-project/serenity/build/../Userland/Libraries/LibCompress/Gzip.cpp:66:1
    #17 0x56c8f3 in Compress::GzipDecompressor::decompress_all(AK::Span<unsigned char const>) /home/lukew/Desktop/serenity-project/serenity/build/../Userland/Libraries/LibCompress/Gzip.cpp:198:1
    #18 0x5633d9 in LLVMFuzzerTestOneInput /home/lukew/Desktop/serenity-project/serenity/build/../Meta/Lagom/Fuzzers/FuzzGzipDecompression.cpp:32:19
    #19 0x46b711 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x46b711)
    #20 0x46ae55 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x46ae55)
    #21 0x46d0f7 in fuzzer::Fuzzer::MutateAndTestOne() (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x46d0f7)
    #22 0x46ddf5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x46ddf5)
    #23 0x45c7ae in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x45c7ae)
    #24 0x4855f2 in main (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x4855f2)
    #25 0x7f9c27a800b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #26 0x43154d in _start (/home/lukew/Desktop/serenity-project/serenity/build/Meta/Lagom/Fuzzers/FuzzGzipDecompression+0x43154d)
```

**Comment by IdanHo** [comment]
Is this after #5818? Since that should have fixed that.

**Comment by Lubrsi** [comment]
Yeah, it's on latest master. I incorporated it into test-compress to test inside serenity:
```
TEST_CASE(gzip_decompress_simple)
{
    const Array<u8, 92> compressed {
        0x1f, 0x8b, 0x08, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x65, 0x1f, 0xe0, 0x00, 0x42,
        0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42,
        0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42,
        0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42,
        0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42,
        0x42, 0x42, 0x42, 0x03, 0x08, 0x84, 0x00, 0x28, 0x8B, 0x1F, 0x8B, 0x2D
    };

    const u8 uncompressed[] = "word1 abc word2";

    const auto decompressed = Compress::GzipDecompressor::decompress_all(compressed);
    EXPECT(decompressed.value().bytes() == (ReadonlyBytes { uncompressed, sizeof(uncompressed) - 1 }));
}
```
And it gives the same result:
```
test-compress(29): Completed test 'zlib_decompress_simple' in 0ms
test-compress(29): USERSPACE(29) ASSERTION FAILED: !has_any_error()
../.././AK/Stream.h:40
CrashDaemon(20): --- Backtrace for thread #0 (TID 29) ---
CrashDaemon(20): 0x76646188: [libsystem.so]  +0x8 (syscall.cpp:35)
CrashDaemon(20): 0x368d8c56: [libc.so] __assertion_failed +0x106 (syscall.h:44)
CrashDaemon(20): 0x2d51fd8f: [libcompress.so] Compress::DeflateDecompressor::~DeflateDecompressor() +0x7f (Stream.h:40)
CrashDaemon(20): 0x2d52b8bc: [libcompress.so] Compress::GzipDecompressor::~GzipDecompressor() +0x7c (Gzip.h:76)
CrashDaemon(20): 0x2d52c396: [libcompress.so] Compress::GzipDecompressor::decompress_all(AK::Span<unsigned char const>) +0x326 (Stream.h:76)
CrashDaemon(20): 0x29a2ed1e: [/bin/test-compress] __test_gzip_decompress_simple() +0x8e (Optional.h:137)
CrashDaemon(20): 0x29a20266: [/bin/test-compress] AK::TestSuite::run(AK::NonnullRefPtrVector<AK::TestCase, 0ul> const&) +0x316 (TestSuite.h:87)
CrashDaemon(20): 0x29a1f38e: [/bin/test-compress] AK::TestSuite::main(AK::String const&, int, char**) +0x29e (TestSuite.h:186)
CrashDaemon(20): 0x29a1f7f6: [/bin/test-compress] main +0x66 (test-compress.cpp:285)
CrashDaemon(20): 0x29a1fc65: [/bin/test-compress] _start +0x45 (crt0_shared.cpp:60)
```
