### ISSUE TITLE
LibJS: has_super_binding() assertion failure in LexicalEnvironment::get_super_base

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#7044]
Found with Fuzzilli.
Code:
```js
function main() {
const v1 = class V1 extends Uint16Array {
    constructor(v3,v4) {
        const v5 = super.keys();
    }
    asUintN(v7,v8) {
    }
};
const v9 = new v1();
}
main();
// STDERR:
// FuzzilliJs: ../Userland/Libraries/LibJS/Runtime/LexicalEnvironment.cpp:72: JS::Value JS::LexicalEnvironment::get_super_base(): Assertion `has_super_binding()' failed.
```
As file: [program_20210511205110_D44EA9C7-A26F-4B18-9060-F8B22606215D_deterministic_6.txt](https://github.com/SerenityOS/serenity/files/6461641/program_20210511205110_D44EA9C7-A26F-4B18-9060-F8B22606215D_deterministic_6.txt)

Trace:
```
js(29:29): USERSPACE(29) ASSERTION FAILED: has_super_binding()
../../Userland/Libraries/LibJS/Runtime/LexicalEnvironment.cpp:72
CrashDaemon(16:16): --- Backtrace for thread #0 (TID 29) ---
CrashDaemon(16:16): 0x9965a1ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
CrashDaemon(16:16): 0x81e17640: [libc.so] kill +0x20 (signal.cpp:21)
CrashDaemon(16:16): 0x81e176e3: [libc.so] raise +0x23 (signal.cpp:34)
CrashDaemon(16:16): 0x81e0276d: [libc.so] abort +0x2a (stdlib.cpp:232)
CrashDaemon(16:16): 0x81e0327b: [libc.so] __assertion_failed +0xeb (Format.h:236)
CrashDaemon(16:16): 0x6c45bc8f: [libjs.so] JS::LexicalEnvironment::get_super_base() +0x8f (LexicalEnvironment.cpp:72)
CrashDaemon(16:16): 0x6c3cd0f8: [libjs.so] JS::CallExpression::compute_this_and_callee(JS::Interpreter&, JS::GlobalObject&) const +0x198 (Value.h:59)
CrashDaemon(16:16): 0x6c3cdd0c: [libjs.so] JS::CallExpression::execute(JS::Interpreter&, JS::GlobalObject&) const +0x8c (VM.h:66)
CrashDaemon(16:16): 0x6c3c951f: [libjs.so] JS::VariableDeclaration::execute(JS::Interpreter&, JS::GlobalObject&) const +0x10f (Atomic.h:246)
CrashDaemon(16:16): 0x6c3e3d07: [libjs.so] JS::Interpreter::execute_statement(JS::GlobalObject&, JS::Statement const&, JS::ScopeType) +0xa7 (Interpreter.cpp:149)
CrashDaemon(16:16): 0x6c496c9f: [libjs.so] JS::ScriptFunction::execute_function_body() +0x2ef (ScriptFunction.cpp:130)
CrashDaemon(16:16): 0x6c4971dd: [libjs.so] JS::ScriptFunction::construct(JS::Function&) +0x16d (ScriptFunction.cpp:148)
CrashDaemon(16:16): 0x6c4bf1f9: [libjs.so] JS::VM::construct(JS::Function&, JS::Function&, AK::Optional<JS::MarkedValueList>, JS::GlobalObject&) +0x2d9 (VM.cpp:244)
CrashDaemon(16:16): 0x6c3ce7ec: [libjs.so] JS::CallExpression::execute(JS::Interpreter&, JS::GlobalObject&) const +0xb6c (AST.cpp:219)
CrashDaemon(16:16): 0x6c3c951f: [libjs.so] JS::VariableDeclaration::execute(JS::Interpreter&, JS::GlobalObject&) const +0x10f (Atomic.h:246)
CrashDaemon(16:16): 0x6c3e3d07: [libjs.so] JS::Interpreter::execute_statement(JS::GlobalObject&, JS::Statement const&, JS::ScopeType) +0xa7 (Interpreter.cpp:149)
CrashDaemon(16:16): 0x6c496c9f: [libjs.so] JS::ScriptFunction::execute_function_body() +0x2ef (ScriptFunction.cpp:130)
CrashDaemon(16:16): 0x6c49701d: [libjs.so] JS::ScriptFunction::call() +0x16d (ScriptFunction.cpp:139)
CrashDaemon(16:16): 0x6c4be8af: [libjs.so] JS::VM::call_internal(JS::Function&, JS::Value, AK::Optional<JS::MarkedValueList>) +0x70f (Vector.h:156)
CrashDaemon(16:16): 0x6c3cea18: [libjs.so] JS::CallExpression::execute(JS::Interpreter&, JS::GlobalObject&) const +0xd98 (VM.h:274)
CrashDaemon(16:16): 0x6c3c6e9f: [libjs.so] JS::ExpressionStatement::execute(JS::Interpreter&, JS::GlobalObject&) const +0xaf (AST.cpp:50)
CrashDaemon(16:16): 0x6c3e3d07: [libjs.so] JS::Interpreter::execute_statement(JS::GlobalObject&, JS::Statement const&, JS::ScopeType) +0xa7 (Interpreter.cpp:149)
CrashDaemon(16:16): 0x6c3c6bac: [libjs.so] JS::Program::execute(JS::Interpreter&, JS::GlobalObject&) const +0xac (AST.cpp:50)
CrashDaemon(16:16): 0x6c3e2a9b: [libjs.so] JS::Interpreter::run(JS::GlobalObject&, JS::Program const&) +0x28b (VM.h:154)
CrashDaemon(16:16): 0x4fee478d: [/bin/js] parse_and_run(JS::Interpreter&, AK::StringView const&) +0x11d (js.cpp:484)
CrashDaemon(16:16): 0x4fedd237: [/bin/js] main +0xb97 (js.cpp:985)
CrashDaemon(16:16): 0x4feddaa8: [/bin/js] _start +0x58 (crt0.cpp:39)
```

**Comment by linusg** [comment]
Simplified repro:

```js
class Foo {
    constructor() {
        super.bar;
    }
}

new Foo();
```

**Comment by linusg** [comment]
Different crash now (environments have been changed a bit recently):

```
js: ../../Userland/Libraries/LibJS/Runtime/Value.h:196: JS::Object& JS::Value::as_object(): Assertion `type() == Type::Object' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7a772a2 in ?? () from /lib64/libc.so.6
#0  0x00007ffff7a772a2 in ?? () from /lib64/libc.so.6
#1  0x00007ffff7a608a4 in ?? () from /lib64/libc.so.6
#2  0x00007ffff7a60789 in ?? () from /lib64/libc.so.6
#3  0x00007ffff7a6fa16 in ?? () from /lib64/libc.so.6
#4  0x000000000055fd98 in JS::Value::as_object (this=<synthetic pointer>) at ../../Userland/Libraries/LibJS/Runtime/Value.h:196
#5  JS::Value::as_object (this=<synthetic pointer>) at ../../Userland/Libraries/LibJS/Runtime/Value.h:194
#6  JS::FunctionEnvironment::get_super_base (this=this@entry=0x7fa240) at ../../Userland/Libraries/LibJS/Runtime/FunctionEnvironment.cpp:38
#7  0x0000000000556fc3 in JS::make_super_property_reference (global_object=..., actual_this=..., property_key=..., strict=<optimized out>)
    at ../../Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp:370
#8  0x00000000004e7cd6 in JS::MemberExpression::to_reference (this=<optimized out>, interpreter=..., global_object=...) at ../../Userland/Libraries/LibJS/AST.cpp:777
#9  0x00000000004e7fdb in JS::MemberExpression::execute (this=0x804dc0, interpreter=..., global_object=...) at ../../Userland/Libraries/LibJS/AST.cpp:1924
#10 0x00000000004e1cf7 in JS::ExpressionStatement::execute (this=0x804f30, interpreter=..., global_object=...) at ../../Userland/Libraries/LibJS/AST.cpp:111
#11 0x00000000004fb61d in JS::Interpreter::execute_statement (this=0x7781b0, global_object=..., statement=..., scope_type=JS::ScopeType::Function)
    at ../../Userland/Libraries/LibJS/Interpreter.cpp:177
#12 0x000000000059847a in JS::OrdinaryFunctionObject::execute_function_body (this=0x7fa140) at ../../Userland/Libraries/LibJS/Runtime/OrdinaryFunctionObject.cpp:227
#13 0x00000000005fc7d2 in JS::VM::construct (this=this@entry=0x765810, function=..., new_target=..., arguments=...) at ../../Userland/Libraries/LibJS/Runtime/VM.cpp:476
#14 0x00000000004ea38c in JS::NewExpression::execute (this=<optimized out>, interpreter=..., global_object=...) at ../../Userland/Libraries/LibJS/AST.cpp:203
#15 0x00000000004e1cf7 in JS::ExpressionStatement::execute (this=0x793e10, interpreter=..., global_object=...) at ../../Userland/Libraries/LibJS/AST.cpp:111
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.33-18.fc34.x86_64 libgcc-11.1.1-3.fc34.x86_64 libstdc++-11.1.1-3.fc34.x86_64
--Type <RET> for more, q to quit, c to continue without paging--
#16 0x00000000004fb61d in JS::Interpreter::execute_statement (this=0x7781b0, global_object=..., statement=..., scope_type=JS::ScopeType::Block) at ../../Userland/Libraries/LibJS/Interpreter.cpp:177
#17 0x00000000004e1c85 in JS::Program::execute (this=this@entry=0x76d880, interpreter=..., global_object=...) at ../../Userland/Libraries/LibJS/AST.cpp:93
#18 0x00000000004fbb31 in JS::Interpreter::run (this=this@entry=0x7781b0, global_object=..., program=...) at ../../Userland/Libraries/LibJS/Interpreter.cpp:60
#19 0x00000000004947cc in parse_and_run (interpreter=..., source=...) at ../../Userland/Utilities/js.cpp:580
#20 0x000000000048cf61 in main (argc=<optimized out>, argv=<optimized out>) at ../../Userland/Utilities/js.cpp:1091
```
