### ISSUE TITLE
Assistant: ../Kernel/Thread.cpp:183 in void Kernel::Thread::block

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#8852]
Running Assistant crashes the kernel.

```
Assistant(31:31): Started thread "", tid = 32
Assistant(31:32): perror(): fstatat: No such file or directory
Assistant(31:32): perror(): fstatat: No such file or directory
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
Assistant(31:32): perror(): fstatat: Bad fd number
[Assistant(31:31)]: ASSERTION FAILED: !m_in_block
[Assistant(31:31)]: ../Kernel/Thread.cpp:183 in void Kernel::Thread::block(Kernel::Mutex&, Kernel::ScopedSpinLock<Kernel::SpinLock<unsigned char> >&, u32)
[#0 Assistant(31:31)]: 0x00000000c0804a43
[#0 Assistant(31:31)]: 0x00000000c080486c
[#0 Assistant(31:31)]: 0x00000000c070d6bd
[#0 Assistant(31:31)]: 0x00000000c04985f1
[#0 Assistant(31:31)]: 0x00000000c049c865
[#0 Assistant(31:31)]: 0x00000000c0701e14
[#0 Assistant(31:31)]: 0x00000000c070f2d1
[#0 Assistant(31:31)]: 0x00000000c04985f1
[#0 Assistant(31:31)]: 0x00000000c049aec2
[#0 Assistant(31:31)]: 0x00000000c03aa15d
[#0 Assistant(31:31)]: 0x00000000c03b3ac2
[#0 Assistant(31:31)]: 0x00000000c045f44a
[#0 Assistant(31:31)]: 0x00000000c04618fe
[#0 Assistant(31:31)]: 0x00000000c046299a
[#0 Assistant(31:31)]: 0x00000000c064e6fe
[#0 Assistant(31:31)]: 0x00000000c05b5263
[#0 Assistant(31:31)]: 0x00000000c05b2f89
```

**Comment by tomuta** [comment]
What revision are you on? I can't seem to be able to replicate this. There was a but that looked just like this but it should have been fixed. But it's entirely possible there's still some edge case. If possible, can you resolve these to file/line for the stack trace?

**Comment by diversys** [comment]
I'm on the latest revision. I forgot to mention that I use x86_64 build running on macOS host.

> If possible, can you resolve these to file/line for the stack trace?

How do I do that?

**Comment by diversys** [comment]
Hm, now the error has changed

[Assistant(32:32)]: ASSERTION FAILED: blocked_thread_list.contains(current_thread)
[Assistant(32:32)]: ../Kernel/Mutex.cpp:213 in void Kernel::Mutex::block(Kernel::Thread&, Kernel::Mutex::Mode, Kernel::ScopedSpinLock<Kernel::SpinLock<unsigned char> >&, u32)

**Comment by tomuta** [comment]
How do you replicate this? Do you search for anything specific in Assistant that triggers it, or is it merely starting Assistant?

I'd be interested in getting a stack trace with resolved file/line information, e.g. using gdb. That would help greatly :)

**Comment by diversys** [comment]
Just merely starting Assistant. I would like to help but I'm not exactly sure how to do that.

**Comment by tomuta** [comment]
Hm it doesn't seem to want to happen for me.

The easiest way to run with gdb is probably to go into the root directory and type:

./Meta/serenity.sh gdb i686

Then, you'll have to click on the bottom pane and hit enter to start continuing the boot process. When you run into this issue then you should be able to get a backtrace from gdb in the bottom pane using the `bt` command. You can copy/paste by holding the shift-key and selecting with the mouse.

**Comment by diversys** [comment]
Running this seems to tried to rebuild everything.

```
./Meta/serenity.sh gdb x86_64
ninja: Entering directory `/Users/diver/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[45/3951] Building CXX object Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Random.cpp.o^C
ninja: build stopped: interrupted by user.
MacBookPro:serenity diver$ ./Meta/serenity.sh gdb i686
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/bin/gcc-10
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/gcc-10 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/g++-10 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Downloading PCI ID database from https://pci-ids.ucw.cz/v2.2/pci.ids.gz...
-- Extracting PCI ID database from /Users/diver/serenity/Build/i686/pci.ids.gz...
-- Downloading USB ID database from http://www.linux-usb.org/usb.ids.gz...
```

**Comment by diversys** [comment]
I see that tmux starts and then it exits immediately.

**Comment by tomuta** [comment]
> I see that tmux starts and then it exits immediately.

Huh weird, not sure what's going on. That works just fine for me.

**Comment by diversys** [comment]
I've rebuilt the world and the problem's gone.

**Comment by diversys** [comment]
Aaand it's back.

```
[Assistant(34:34)]: ASSERTION FAILED: blocked_thread_list.contains(current_thread)
[Assistant(34:34)]: ./Kernel/Mutex.cpp:213 in void Kernel::Mutex::block(Kernel::Thread&, Kernel::Mutex::Mode, Kernel::ScopedSpinLock<Kernel::SpinLock<unsigned char> >&, u32)
```

**Comment by tomuta** [comment]
Sorry you're going to need to try and get a stack trace one way or another. I unfortunately haven't seen it and don't know how I can replicate it.

**Comment by gunnarbeutner** [comment]
`addr2line -e Build/x86_64/Kernel/Kernel` and then paste the addresses from the stacktrace there, like so:

```
$ addr2line -e Kernel/Kernel
0x000000200114d5e7
./Build/x86_64/./Kernel/init.cpp:124
^C
```

**Comment by gunnarbeutner** [comment]
I just managed to reproduce this here (by just starting Assistant):

```
#0  Kernel::halt_this () at ././Kernel/Arch/x86/ASM_wrapper.h:146
#1  Kernel::Processor::halt () at ./Kernel/Arch/x86/common/Processor.cpp:1010
#2  0x0000002000eb73bd in abort () at ./Kernel/Arch/x86/common/CPU.cpp:31
#3  0x0000002000eb71cd in __assertion_failed (msg=<optimized out>, msg@entry=0x200119bff8 "blocked_thread_list.contains(current_thread)", file=<optimized out>, file@entry=0x200119c587 "./Kernel/Mutex.cpp", line=<optimized out>,
    line@entry=213, func=<optimized out>, func@entry=0x200119bf48 "void Kernel::Mutex::block(Kernel::Thread&, Kernel::Mutex::Mode, Kernel::ScopedSpinLock<Kernel::SpinLock<unsigned char> >&, u32)") at ./Kernel/Arch/x86/common/CPU.cpp:19
#4  0x00000020007bfb58 in Kernel::Mutex::block (this=this@entry=0x2001c8bef0 <kmalloc_pool_heap+491248>, current_thread=..., mode=mode@entry=Kernel::LockMode::Exclusive, lock=..., requested_locks=requested_locks@entry=1)
    at ./Kernel/Mutex.cpp:213
#5  0x00000020007c9470 in Kernel::Mutex::lock (this=this@entry=0x2001c8bef0 <kmalloc_pool_heap+491248>, mode=mode@entry=Kernel::LockMode::Exclusive) at ./Kernel/Mutex.cpp:56
#6  0x000000200058a12a in Kernel::MutexLocker::MutexLocker (mode=Kernel::LockMode::Exclusive, l=..., this=0x20037f4980) at ././Kernel/Mutex.h:128
#7  Kernel::BlockBasedFileSystem::read_block (this=this@entry=0x2001c8be50 <kmalloc_pool_heap+491088>, index=99464, buffer=buffer@entry=0x20037f4a60, count=count@entry=71, offset=offset@entry=0, allow_cache=allow_cache@entry=true)
    at ./Kernel/FileSystem/BlockBasedFileSystem.cpp:208
#8  0x0000002000609d34 in Kernel::Ext2FSInode::read_bytes (this=0x20079272f0, offset=<optimized out>, count=<optimized out>, buffer=..., description=<optimized out>) at ./Kernel/FileSystem/Ext2FileSystem.cpp:890
#9  0x00000020006949d0 in Kernel::InodeFile::read (this=this@entry=0x2008266110, description=..., offset=offset@entry=0, buffer=..., count=count@entry=1024) at ./Kernel/FileSystem/InodeFile.cpp:34
#10 0x000000200065f6be in Kernel::FileDescription::read (this=this@entry=0x20082661d0, buffer=..., count=count@entry=1024) at ./Kernel/FileSystem/FileDescription.cpp:182
#11 0x0000002000b8143a in Kernel::Process::sys$read (this=this@entry=0x200799d000, fd=<optimized out>, buffer=..., size=<optimized out>) at ./Kernel/Syscalls/read.cpp:101
#12 0x0000002000a1244c in Kernel::Syscall::handle (regs=..., function=<optimized out>, arg1=<optimized out>, arg2=<optimized out>, arg3=<optimized out>) at ./Kernel/Syscall.cpp:156
#13 0x0000002000a14501 in Kernel::syscall_handler (trap=<optimized out>) at ./Kernel/Syscall.cpp:218
#14 0x0000002000a10124 in Kernel::syscall_asm_entry () at ./Kernel/Syscall.cpp:51
#15 0x0000000000000000 in ?? ()
```

**Comment by tomuta** [comment]
Hm, not sure why this is happening. I found another way to replicate it by starting many Assistant instances rapidly.

**Comment by tomuta** [comment]
@bgianfo It looks like #9034 happens to also fix this issue. At least I can't replicate it anymore when starting multiple Assistant instances (reverting bf16591c077c5d77a8ba8fae2401157a81e18704 to be able to do so)
